angular.module('Yaka')
    .config(['cloudinaryProvider', function (cloudinaryProvider) {
        cloudinaryProvider
            .set("cloud_name", "yaka")
            .set("upload_preset", "cxsdlf5n");
    }])
    .config(['uiGmapGoogleMapApiProvider', function (GoogleMapApi) {
        GoogleMapApi.configure({
            key: 'AIzaSyDtq1oFK_ku6rSm9OHM8Q0MlHeOYzOWgr8',
            libraries: 'weather,geometry,visualization'
            // v: '3.20',
        });
    }])
    .config(['$translateProvider', function (translateProvider) {
        // Simply register translation table as object hash
        translateProvider.useSanitizeValueStrategy('escape');
        translateProvider.translations('en', {
            'ACTIVITY_INSTALLATION': "Installation",
            'ACTIVITY_REPLACEMENT': "Remplacement",
            'ACTIVITY_REPAIR': "Réparation",
            'ACTIVITY_MAINTENANCE': "Maintenance",
            'ACTIVITY_CONSTRUCTION': "Construction",
            'ACTIVITY_RENOVATION': "Rénovation",
            'ACTIVITY_UNCORK': "Déboucher",
            'ACTIVITY_GOOD': "Bon état",
            'ACTIVITY_AVERAGE': "État moyen",
            'ACTIVITY_BAD': "Mauvais état",
            'ACTIVITY_OTHER': "Autre - Je ne sais pas",
            'ACTIVITY_ELE_1000': "Electricité",
            'ACTIVITY_ELE_SHOOTINGWIRING_1010': "Prise / câblage",
            'ACTIVITY_ELE_LIGHTING_1020': "Eclairage",
            'ACTIVITY_ELE_INSIDELIGHTING_1030': "Éclairage intérieur",
            'ACTIVITY_ELE_EXTERIORLIGHTING_1040': "Eclairage extérieur",
            'ACTIVITY_ELE_RADIATORTOWELDRYER_1050': "Radiateur / Sèche serviette",
            'ACTIVITY_ELE_RADIATOR_1060': "Radiateur",
            'ACTIVITY_ELE_DRYTOWEL_1070': "Sèche serviette",
            'ACTIVITY_ELE_BOILERWATERHEATER_1080': "Chaudière / chauffe-eau",
            'ACTIVITY_ELE_BOILER_1090': "Chaudière",
            'ACTIVITY_ELE_WATERHEATER_1100': "Chauffe-eau",
            'ACTIVITY_ELE_HOTWATERTANK_1110': "Ballon d'eau chaude",
            'ACTIVITY_ELE_SWITCHBOARD_1120': "Tableau électrique",
            'ACTIVITY_ELE_ELECTRICMETER_1130': "Compteur électrique",
            'ACTIVITY_ELE_AUTOMATION_1140': "Domotique",
            'ACTIVITY_ELE_SECURITYALARMINTERCOM_1150': "Sécurité / Alarmes / Interphone",
            'ACTIVITY_ELE_ALARMS_1160': "Alarmes",
            'ACTIVITY_ELE_VIDEOSURVEILLANCE_1170': "Vidéo surveillance",
            'ACTIVITY_ELE_INTERCOM_1180': "Interphone",
            'ACTIVITY_ELE_KEYPAD_1190': "Digicode",
            'ACTIVITY_ELE_SMOKEDETECTOR_1200': "Détecteur de fumée",
            'ACTIVITY_PLU_2000': "Plomberie",
            'ACTIVITY_PLU_BATHROOM_2010': "Toilettes",
            'ACTIVITY_PLU_CLASSICAL_2020': "Classique",
            'ACTIVITY_PLU_CUSPENDU_2030': "Cuspendu",
            'ACTIVITY_PLU_MECHANISM_2040': "Mécanisme",
            'ACTIVITY_PLU_SHOWER_2050': "Douche",
            'ACTIVITY_PLU_CABIN_2060': "Cabine",
            'ACTIVITY_PLU_COLUMN_2070': "Colonne",
            'ACTIVITY_PLU_DOOR_2080': "Porte",
            'ACTIVITY_PLU_SHOWERSCREEN_2090': "Pare-douche",
            'ACTIVITY_PLU_BATH_2100': "Baignoire",
            'ACTIVITY_PLU_BATH_2110': "Baignoire",
            'ACTIVITY_PLU_FAUCETMIXER_2120': "Robinet / Mitigeur",
            'ACTIVITY_PLU_BATHSCREEN_2130': "Pare-baignoire",
            'ACTIVITY_PLU_SINKSINK_2140': "Lavabo / Évier",
            'ACTIVITY_PLU_PIPESEWER_2150': "Tuyauterie / Canalisation",
            'ACTIVITY_PLU_BOILERWATERHEATERHOTWATERTANK_2160': "Chaudière / Chauffe-eau / Ballon d'eau chaude",
            'ACTIVITY_PLU_BOILER_2170': "Chaudière",
            'ACTIVITY_PLU_WATERHEATER_2180': "Chauffe-eau",
            'ACTIVITY_PLU_HOTWATERTANK_2190': "Ballon d'eau chaude",
            'ACTIVITY_PLU_SOFTENER_2200': "Adoucisseur",
            'ACTIVITY_HEA_3000': "Chauffage / Climatisation",
            'ACTIVITY_HEA_BOILERWATERHEATERHOTWATERTANK_3010': "Chaudière / Chauffe-eau / Ballon d'eau chaude",
            'ACTIVITY_HEA_BOILER_3020': "Chaudière",
            'ACTIVITY_HEA_WATERHEATER_3030': "Chauffe-eau",
            'ACTIVITY_HEA_HOTWATERTANK_3040': "Ballon d'eau chaude",
            'ACTIVITY_HEA_RADIATORTOWELDRYER_3050': "Radiateur / Sèche serviette",
            'ACTIVITY_HEA_ELECTRICHEATER_3060': "Radiateur électrique",
            'ACTIVITY_HEA_GASHEATER_3070': "Radiateur gaz",
            'ACTIVITY_HEA_ELECTRICTOWELRAIL_3080': "Sèche serviette électrique",
            'ACTIVITY_HEA_TOWELDRYGAS_3090': "Sèche serviette gaz",
            'ACTIVITY_HEA_FLOORHEATING_3100': "Chauffage au sol",
            'ACTIVITY_HEA_THERMOSTAT_3110': "Thermostat",
            'ACTIVITY_HEA_AIRCONDITIONER_3120': "Climatisation",
            'ACTIVITY_HEA_HEATPUMP_3130': "Pompe à chaleur",
            'ACTIVITY_HEA_STOVEINSERTSFIREPLACES_3140': "Poêle / Inserts / Cheminée",
            'ACTIVITY_HEA_HEARTH_3150': "Poêle a bois",
            'ACTIVITY_HEA_PELLETSTOVE_3160': "Poêle à granulés",
            'ACTIVITY_HEA_FIREPLACE_3170': "Cheminée",
            'ACTIVITY_HEA_INSERT_3180': "Insert",
            'ACTIVITY_HEA_VMC_3190': "VMC",
            'ACTIVITY_HEA_VMCSINGLEFLOW_3200': "VMC simple flux",
            'ACTIVITY_HEA_VMCDOUBLEFLOW_3210': "VMC Double flux",
            'ACTIVITY_CAR_4000': "Menuiserie / Fenêtre / Véranda",
            'ACTIVITY_CAR_SINGLEDOOR_4010': "Porte simple",
            'ACTIVITY_CAR_PLASTICPVC_4020': "Plastic / PVC",
            'ACTIVITY_CAR_METALALU_4030': "Métal / Alu",
            'ACTIVITY_CAR_WOOD_4040': "Bois",
            'ACTIVITY_CAR_REINFORCEDDOOR_4050': "Porte blindée",
            'ACTIVITY_CAR_PLASTICPVC_4060': "Plastic / PVC",
            'ACTIVITY_CAR_METALALU_4070': "Métal / Alu",
            'ACTIVITY_CAR_WOOD_4080': "Bois",
            'ACTIVITY_CAR_ROOFWINDOWSKYLIGHT_4090': "Fenêtre de toit / Velux",
            'ACTIVITY_CAR_WINDOW_4100': "Fenêtre",
            'ACTIVITY_CAR_SINGLEGLAZING_4110': "Simple vitrage",
            'ACTIVITY_CAR_DOUBLEGLAZING_4120': "Double vitrage",
            'ACTIVITY_CAR_DOORWINDOW_4130': "Porte fenêtre",
            'ACTIVITY_CAR_SINGLEGLAZING_4140': "Simple vitrage",
            'ACTIVITY_CAR_DOUBLEGLAZING_4150': "Double vitrage",
            'ACTIVITY_CAR_SHUTTERS_4160': "Volets",
            'ACTIVITY_CAR_ELECTRICSHUTTERS_4170': "Volets roulants électriques",
            'ACTIVITY_CAR_MANUALSHUTTERS_4180': "Volets roulants manuels",
            'ACTIVITY_CAR_SHUTTERS_4190': "Volets battants",
            'ACTIVITY_CAR_STAIRCASE_4200': "Escalier",
            'ACTIVITY_CAR_MEZZANINE_4210': "Mezzanine",
            'ACTIVITY_CAR_CUPBOARDSCUPBOARDS_4220': "Placards / Rangements",
            'ACTIVITY_CAR_VERANDA_4230': "Véranda",
            'ACTIVITY_LOC_5000': "Serrurerie",
            'ACTIVITY_LOC_SINGLEDOOR_5010': "Porte simple",
            'ACTIVITY_LOC_PLASTICPVC_5020': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5030': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5040': "Bois",
            'ACTIVITY_LOC_REINFORCEDDOOR_5050': "Porte blindée",
            'ACTIVITY_LOC_PLASTICPVC_5060': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5070': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5080': "Bois",
            'ACTIVITY_LOC_CONVENTIONALLOCK_5090': "Serrure classique",
            'ACTIVITY_LOC_PLASTICPVC_5100': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5110': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5120': "Bois",
            'ACTIVITY_LOC_MULTI-POINTLOCK_5130': "Serrure multi-points",
            'ACTIVITY_LOC_PLASTICPVC_5140': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5150': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5160': "Bois",
            'ACTIVITY_LOC_ELECTRICSTRIKE_5170': "Gâche électrique",
            'ACTIVITY_LOC_SHUTTERS_5180': "Volets roulants",
            'ACTIVITY_LOC_METALLICCURTAINS_5190': "Rideaux Métallique",
            'ACTIVITY_PAI_6000': "Peinture, murs et sols",
            'ACTIVITY_PAI_WALLPAPER_6010': "Papier peint",
            'ACTIVITY_PAI_LESSTHAN30M_6020': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6030': "Plus de 30m²",
            'ACTIVITY_PAI_INTERIORPAINT_6040': "Peinture intérieur",
            'ACTIVITY_PAI_LESSTHAN30M_6050': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6060': "Plus de 30m²",
            'ACTIVITY_PAI_DECORATIVEINTERIORPLASTER_6070': "Enduit d'intérieur décoratif",
            'ACTIVITY_PAI_LESSTHAN30M_6080': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6090': "Plus de 30m²",
            'ACTIVITY_PAI_EXTERIORPAINTING_6100': "Peinture extérieure",
            'ACTIVITY_PAI_LESSTHAN30M_6110': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6120': "Plus de 30m²",
            'ACTIVITY_PAI_EXTERIORCOATING_6130': "Enduit d'extérieur",
            'ACTIVITY_PAI_LESSTHAN30M_6140': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6150': "Plus de 30m²",
            'ACTIVITY_PAI_INTERIORFLOOR_6160': "Sol intérieur",
            'ACTIVITY_PAI_FLOORTILE_6170': "Carrelage",
            'ACTIVITY_PAI_LESSTHAN20M_6180': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6190': "Plus de 20m²",
            'ACTIVITY_PAI_PARQUET_6200': "Parquet",
            'ACTIVITY_PAI_LESSTHAN20M_6210': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6220': "Plus de 20m²",
            'ACTIVITY_PAI_CARPET_6230': "Moquette",
            'ACTIVITY_PAI_LESSTHAN20M_6240': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6250': "Plus de 20m²",
            'ACTIVITY_PAI_PLASTICFLOOR_6260': "Sol plastique",
            'ACTIVITY_PAI_LESSTHAN20M_6270': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6280': "Plus de 20m²",
            'ACTIVITY_PAI_PIERRE_6290': "Pierre",
            'ACTIVITY_PAI_LESSTHAN20M_6300': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6310': "Plus de 20m²",
            'ACTIVITY_PAI_CONCRETE_6320': "Béton",
            'ACTIVITY_PAI_LESSTHAN20M_6330': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6340': "Plus de 20m²",
            'ACTIVITY_PAI_OUTDOORFLOOR_6350': "Sol extérieur",
            'ACTIVITY_PAI_FLOORTILE_6360': "Carrelage",
            'ACTIVITY_PAI_LESSTHAN20M_6370': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6380': "Plus de 20m²",
            'ACTIVITY_PAI_PIERRE_6390': "Pierre",
            'ACTIVITY_PAI_LESSTHAN20M_6400': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6410': "Plus de 20m²",
            'ACTIVITY_PAI_CONCRETE_6420': "Béton",
            'ACTIVITY_PAI_LESSTHAN20M_6430': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6440': "Plus de 20m²",
            'ACTIVITY_WAL_7000': "Cloisons / Plafonds / Combles",
            'ACTIVITY_WAL_PARTITIONS_7010': "Cloisons",
            'ACTIVITY_WAL_CEILINGS_7020': "Plafonds",
            'ACTIVITY_WAL_LOFT_7030': "Combles",
            'ACTIVITY_WAL_INSULATION_7040': "Isolation",
            'ACTIVITY_WAL_PLANNING_7050': "Aménagement",
            'ACTIVITY_WAL_PLANNINGANDINSULATION_7060': "Aménagement et isolation",
            'ACTIVITY_INS_8000': "Isolation",
            'ACTIVITY_INS_INTERIORINSULATION_8010': "Isolation thermique intérieure",
            'ACTIVITY_INS_EXTERNALTHERMALINSULATION_8020': "Isolation thermique extérieure",
            'ACTIVITY_INS_LOFTINSULATION_8030': "Isolation des combles",
            'ACTIVITY_INS_SOUNDPROOFING_8040': "Isolation phonique",
            'ACTIVITY_COU_9000': "Conseil, architecte et paysagiste",
            'ACTIVITY_COU_ARCHITECT_9010': "Architecte",
            'ACTIVITY_COU_DECORATIONHOMEIMPROVEMENT_9020': "Décoration / Aménagement d'intérieur",
            'ACTIVITY_COU_LANDSCAPER_9030': "Paysagiste",
            'ACTIVITY_KIT_10000': "Cuisine / Salle de Bain",
            'ACTIVITY_KIT_KITCHENROOM_10010': "Cuisine",
            'ACTIVITY_KIT_FULLKITCHEN_10020': "Cuisine complète",
            'ACTIVITY_KIT_KITCHENFURNITURE_10030': "Meubles de cuisines",
            'ACTIVITY_KIT_WORKPLAN_10040': "Plan de travail",
            'ACTIVITY_KIT_BATHROOM_10050': "Salle de bain",
            'ACTIVITY_KIT_BATHROOM_10060': "Salle de bain complète",
            'ACTIVITY_KIT_BATHROOMFURNITURE_10070': "Meubles de salle de bains",
            'ACTIVITY_ROO_11000': "Toiture / Charpente",
            'ACTIVITY_ROO_ROOFING_11010': "Toiture",
            'ACTIVITY_ROO_TERRACE_11020': "Terrasse",
            'ACTIVITY_ROO_TILE_11030': "Tuile",
            'ACTIVITY_ROO_SLATE_11040': "Ardoise",
            'ACTIVITY_ROO_ZINC_11050': "Zinc",
            'ACTIVITY_ROO_SHINGLE_11060': "Shingle",
            'ACTIVITY_ROO_SHEETMETAL_11070': "Tôle",
            'ACTIVITY_ROO_THATCH_11080': "Chaume",
            'ACTIVITY_ROO_WOODENROOFS_11090': "Charpente bois",
            'ACTIVITY_ROO_METALFRAME_11100': "Charpente métallique",
            'ACTIVITY_GAT_12000': "Portail / Porte de garage",
            'ACTIVITY_GAT_PORTAL_12010': "Portail",
            'ACTIVITY_GAT_PLASTICPVC_12020': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12030': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12040': "Bois",
            'ACTIVITY_GAT_ELECTRICGATE_12050': "Portail électrique",
            'ACTIVITY_GAT_PLASTICPVC_12060': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12070': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12080': "Bois",
            'ACTIVITY_GAT_GARAGEDOOR_12090': "Porte de garage",
            'ACTIVITY_GAT_PLASTICPVC_12100': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12110': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12120': "Bois",
            'ACTIVITY_GAT_ELECTRICGARAGEDOOR_12130': "Porte de garage électrique",
            'ACTIVITY_GAT_PLASTICPVC_12140': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12150': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12160': "Bois",
            'ACTIVITY_GAR_13000': "Jardin / Terrase / Clôture",
            'ACTIVITY_GAR_GARDENANDGREENSPACES_13010': "Jardin et d'espaces verts",
            'ACTIVITY_GAR_WOODENDECK_13020': "Terrasse en bois",
            'ACTIVITY_GAR_FENCED_13030': "Clôture",
            'ACTIVITY_GAR_GRILLING_13040': "Grillage",
            'ACTIVITY_GAR_CANNISSE_13050': "Cannisse",
            'ACTIVITY_GAR_WOODPANELS_13060': "Panneaux bois",
            'ACTIVITY_GAR_PVCPANELS_13070': "Panneaux PVC",
            'ACTIVITY_GAR_WALLMURET_13080': "Mur / Muret",
            'ACTIVITY_GAR_CINDERBLOCK_13090': "Parpaing",
            'ACTIVITY_GAR_BRICK_13100': "Brique",
            'ACTIVITY_GAR_WOODFRAME_13110': "Ossature bois",
            'ACTIVITY_GAR_METAL_13120': "Métal",
            'ACTIVITY_GAR_EARTHWORK_13130': "Terrassement",
            'ACTIVITY_CON_14000': "Construction",
            'ACTIVITY_CON_HOUSE_14010': "Maison",
            'ACTIVITY_CON_TRADTIONNELLECONCRETEBLOCK_14020': "Tradtionnelle (parpaing)",
            'ACTIVITY_CON_INBRICK_14030': "En brique",
            'ACTIVITY_CON_WOODFRAME_14040': "Ossature bois",
            'ACTIVITY_CON_BBC_14050': "BBC",
            'ACTIVITY_CON_GARAGE_14060': "Garage",
            'ACTIVITY_CON_CONCRETE_14070': "Béton",
            'ACTIVITY_CON_BRICK_14080': "Brique",
            'ACTIVITY_CON_WOODFRAME_14090': "Ossature bois",
            'ACTIVITY_CON_METAL_14100': "Métal",
            'ACTIVITY_CON_HOUSEEXTENSION_14110': "Extension de maison",
            'ACTIVITY_CON_CINDERBLOCK_14120': "Parpaing",
            'ACTIVITY_CON_BRICK_14130': "Brique",
            'ACTIVITY_CON_WOODFRAME_14140': "Ossature bois",
            'ACTIVITY_CON_FOUNDATIONS_14150': "Fondations",
            'ACTIVITY_CON_SWIMMINGPOOL_14160': "Piscine"
        });
        translateProvider.translations('fr', {
            'ACTIVITY_INSTALLATION': "Installation",
            'ACTIVITY_REPLACEMENT': "Remplacement",
            'ACTIVITY_REPAIR': "Réparation",
            'ACTIVITY_MAINTENANCE': "Maintenance",
            'ACTIVITY_CONSTRUCTION': "Construction",
            'ACTIVITY_RENOVATION': "Rénovation",
            'ACTIVITY_UNCORK': "Déboucher",
            'ACTIVITY_GOOD': "Bon état",
            'ACTIVITY_AVERAGE': "État moyen",
            'ACTIVITY_BAD': "Mauvais état",
            'ACTIVITY_OTHER': "Autre - Je ne sais pas",
            'ACTIVITY_ELE_1000': "Electricité",
            'ACTIVITY_ELE_SHOOTINGWIRING_1010': "Prise / câblage",
            'ACTIVITY_ELE_LIGHTING_1020': "Eclairage",
            'ACTIVITY_ELE_INSIDELIGHTING_1030': "Éclairage intérieur",
            'ACTIVITY_ELE_EXTERIORLIGHTING_1040': "Eclairage extérieur",
            'ACTIVITY_ELE_RADIATORTOWELDRYER_1050': "Radiateur / Sèche serviette",
            'ACTIVITY_ELE_RADIATOR_1060': "Radiateur",
            'ACTIVITY_ELE_DRYTOWEL_1070': "Sèche serviette",
            'ACTIVITY_ELE_BOILERWATERHEATER_1080': "Chaudière / chauffe-eau",
            'ACTIVITY_ELE_BOILER_1090': "Chaudière",
            'ACTIVITY_ELE_WATERHEATER_1100': "Chauffe-eau",
            'ACTIVITY_ELE_HOTWATERTANK_1110': "Ballon d'eau chaude",
            'ACTIVITY_ELE_SWITCHBOARD_1120': "Tableau électrique",
            'ACTIVITY_ELE_ELECTRICMETER_1130': "Compteur électrique",
            'ACTIVITY_ELE_AUTOMATION_1140': "Domotique",
            'ACTIVITY_ELE_SECURITYALARMINTERCOM_1150': "Sécurité / Alarmes / Interphone",
            'ACTIVITY_ELE_ALARMS_1160': "Alarmes",
            'ACTIVITY_ELE_VIDEOSURVEILLANCE_1170': "Vidéo surveillance",
            'ACTIVITY_ELE_INTERCOM_1180': "Interphone",
            'ACTIVITY_ELE_KEYPAD_1190': "Digicode",
            'ACTIVITY_ELE_SMOKEDETECTOR_1200': "Détecteur de fumée",
            'ACTIVITY_PLU_2000': "Plomberie",
            'ACTIVITY_PLU_BATHROOM_2010': "Toilettes",
            'ACTIVITY_PLU_CLASSICAL_2020': "Classique",
            'ACTIVITY_PLU_CUSPENDU_2030': "Cuspendu",
            'ACTIVITY_PLU_MECHANISM_2040': "Mécanisme",
            'ACTIVITY_PLU_SHOWER_2050': "Douche",
            'ACTIVITY_PLU_CABIN_2060': "Cabine",
            'ACTIVITY_PLU_COLUMN_2070': "Colonne",
            'ACTIVITY_PLU_DOOR_2080': "Porte",
            'ACTIVITY_PLU_SHOWERSCREEN_2090': "Pare-douche",
            'ACTIVITY_PLU_BATH_2100': "Baignoire",
            'ACTIVITY_PLU_BATH_2110': "Baignoire",
            'ACTIVITY_PLU_TAPFAUCET_2120': "Robinet / mitigeur",
            'ACTIVITY_PLU_BATHSCREEN_2130': "Pare-baignoire",
            'ACTIVITY_PLU_BASINSINK_2140': "Lavabo/évier",
            'ACTIVITY_PLU_PLUMBINGPIPING_2150': "Tuyauterie/canalisation",
            'ACTIVITY_PLU_BOILERWATERHEATERHOTWATERTANK_2160': "Chaudière/chauffe-eau/ballon d'eau chaude",
            'ACTIVITY_PLU_BOILER_2170': "Chaudière",
            'ACTIVITY_PLU_WATERHEATER_2180': "Chauffe-eau",
            'ACTIVITY_PLU_HOTWATERTANK_2190': "Ballon d'eau chaude",
            'ACTIVITY_PLU_SOFTENER_2200': "Adoucisseur",
            'ACTIVITY_HEA_3000': "Chauffage / Climatisation",
            'ACTIVITY_HEA_BOILERWATERHEATERHOTWATERTANK_3010': "Chaudière / chauffe-eau / ballon d'eau chaude",
            'ACTIVITY_HEA_BOILER_3020': "Chaudière",
            'ACTIVITY_HEA_WATERHEATER_3030': "Chauffe-eau",
            'ACTIVITY_HEA_HOTWATERTANK_3040': "Ballon d'eau chaude",
            'ACTIVITY_HEA_RADIATORTOWELDRYER_3050': "Radiateur / Sèche serviette",
            'ACTIVITY_HEA_ELECTRICHEATER_3060': "Radiateur électrique",
            'ACTIVITY_HEA_GASHEATER_3070': "Radiateur gaz",
            'ACTIVITY_HEA_ELECTRICTOWELRAIL_3080': "Sèche serviette électrique",
            'ACTIVITY_HEA_TOWELDRYGAS_3090': "Sèche serviette gaz",
            'ACTIVITY_HEA_FLOORHEATING_3100': "Chauffage au sol",
            'ACTIVITY_HEA_THERMOSTAT_3110': "Thermostat",
            'ACTIVITY_HEA_AIRCONDITIONER_3120': "Climatisation",
            'ACTIVITY_HEA_HEATPUMP_3130': "Pompe à chaleur",
            'ACTIVITY_HEA_STOVEINSERTFIREPLACE_3140': "Poêle / inserts / cheminée",
            'ACTIVITY_HEA_HEARTH_3150': "Poêle a bois",
            'ACTIVITY_HEA_PELLETSTOVE_3160': "Poêle à granulés",
            'ACTIVITY_HEA_FIREPLACE_3170': "Cheminée",
            'ACTIVITY_HEA_INSERT_3180': "Insert",
            'ACTIVITY_HEA_VMC_3190': "VMC",
            'ACTIVITY_HEA_VMCSINGLEFLOW_3200': "VMC simple flux",
            'ACTIVITY_HEA_VMCDOUBLEFLOW_3210': "VMC Double flux",
            'ACTIVITY_CAR_4000': "Menuiserie / Fenêtre / Véranda",
            'ACTIVITY_CAR_SINGLEDOOR_4010': "Porte simple",
            'ACTIVITY_CAR_PLASTICPVC_4020': "Plastic / PVC",
            'ACTIVITY_CAR_METALALU_4030': "Métal / Alu",
            'ACTIVITY_CAR_WOOD_4040': "Bois",
            'ACTIVITY_CAR_REINFORCEDDOOR_4050': "Porte blindée",
            'ACTIVITY_CAR_PLASTICPVC_4060': "Plastic / PVC",
            'ACTIVITY_CAR_METALALU_4070': "Métal / Alu",
            'ACTIVITY_CAR_WOOD_4080': "Bois",
            'ACTIVITY_CAR_ROOFWINDOWSKYLIGHT_4090': "Fenêtre de toit / Velux",
            'ACTIVITY_CAR_WINDOW_4100': "Fenêtre",
            'ACTIVITY_CAR_SINGLEGLAZING_4110': "Simple vitrage",
            'ACTIVITY_CAR_DOUBLEGLAZING_4120': "Double vitrage",
            'ACTIVITY_CAR_DOORWINDOW_4130': "Porte fenêtre",
            'ACTIVITY_CAR_SINGLEGLAZING_4140': "Simple vitrage",
            'ACTIVITY_CAR_DOUBLEGLAZING_4150': "Double vitrage",
            'ACTIVITY_CAR_SHUTTERS_4160': "Volets",
            'ACTIVITY_CAR_ELECTRICSHUTTERS_4170': "Volets roulants électriques",
            'ACTIVITY_CAR_MANUALSHUTTERS_4180': "Volets roulants manuels",
            'ACTIVITY_CAR_SHUTTERS_4190': "Volets battants",
            'ACTIVITY_CAR_STAIRCASE_4200': "Escalier",
            'ACTIVITY_CAR_MEZZANINE_4210': "Mezzanine",
            'ACTIVITY_CAR_CLOSETSCUPBOARDS_4220': "Placards /rangements",
            'ACTIVITY_CAR_VERANDA_4230': "Véranda",
            'ACTIVITY_LOC_5000': "Serrurerie",
            'ACTIVITY_LOC_SINGLEDOOR_5010': "Porte simple",
            'ACTIVITY_LOC_PLASTICPVC_5020': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5030': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5040': "Bois",
            'ACTIVITY_LOC_REINFORCEDDOOR_5050': "Porte blindée",
            'ACTIVITY_LOC_PLASTICPVC_5060': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5070': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5080': "Bois",
            'ACTIVITY_LOC_CONVENTIONALLOCK_5090': "Serrure classique",
            'ACTIVITY_LOC_PLASTICPVC_5100': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5110': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5120': "Bois",
            'ACTIVITY_LOC_MULTI-POINTLOCK_5130': "Serrure multi-points",
            'ACTIVITY_LOC_PLASTICPVC_5140': "Plastic / PVC",
            'ACTIVITY_LOC_METALALU_5150': "Métal / Alu",
            'ACTIVITY_LOC_WOOD_5160': "Bois",
            'ACTIVITY_LOC_ELECTRICSTRIKE_5170': "Gâche électrique",
            'ACTIVITY_LOC_SHUTTERS_5180': "Volets roulants",
            'ACTIVITY_LOC_METALLICCURTAINS_5190': "Rideaux Métallique",
            'ACTIVITY_PAI_6000': "Peinture, murs et sols",
            'ACTIVITY_PAI_WALLPAPER_6010': "Papier peint",
            'ACTIVITY_PAI_LESSTHAN30M_6020': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6030': "Plus de 30m²",
            'ACTIVITY_PAI_INTERIORPAINT_6040': "Peinture intérieur",
            'ACTIVITY_PAI_LESSTHAN30M_6050': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6060': "Plus de 30m²",
            'ACTIVITY_PAI_DECORATIVEINTERIORPLASTER_6070': "Enduit d'intérieur décoratif",
            'ACTIVITY_PAI_LESSTHAN30M_6080': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6090': "Plus de 30m²",
            'ACTIVITY_PAI_EXTERIORPAINTING_6100': "Peinture extérieure",
            'ACTIVITY_PAI_LESSTHAN30M_6110': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6120': "Plus de 30m²",
            'ACTIVITY_PAI_EXTERIORCOATING_6130': "Enduit d'extérieur",
            'ACTIVITY_PAI_LESSTHAN30M_6140': "Moins de 30m²",
            'ACTIVITY_PAI_MORETHAN30M_6150': "Plus de 30m²",
            'ACTIVITY_PAI_INTERIORFLOOR_6160': "Sol intérieur",
            'ACTIVITY_PAI_FLOORTILE_6170': "Carrelage",
            'ACTIVITY_PAI_LESSTHAN20M_6180': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6190': "Plus de 20m²",
            'ACTIVITY_PAI_PARQUET_6200': "Parquet",
            'ACTIVITY_PAI_LESSTHAN20M_6210': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6220': "Plus de 20m²",
            'ACTIVITY_PAI_CARPET_6230': "Moquette",
            'ACTIVITY_PAI_LESSTHAN20M_6240': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6250': "Plus de 20m²",
            'ACTIVITY_PAI_PLASTICFLOOR_6260': "Sol plastique",
            'ACTIVITY_PAI_LESSTHAN20M_6270': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6280': "Plus de 20m²",
            'ACTIVITY_PAI_PIERRE_6290': "Pierre",
            'ACTIVITY_PAI_LESSTHAN20M_6300': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6310': "Plus de 20m²",
            'ACTIVITY_PAI_CONCRETE_6320': "Béton",
            'ACTIVITY_PAI_LESSTHAN20M_6330': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6340': "Plus de 20m²",
            'ACTIVITY_PAI_OUTDOORFLOOR_6350': "Sol extérieur",
            'ACTIVITY_PAI_FLOORTILE_6360': "Carrelage",
            'ACTIVITY_PAI_LESSTHAN20M_6370': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6380': "Plus de 20m²",
            'ACTIVITY_PAI_PIERRE_6390': "Pierre",
            'ACTIVITY_PAI_LESSTHAN20M_6400': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6410': "Plus de 20m²",
            'ACTIVITY_PAI_CONCRETE_6420': "Béton",
            'ACTIVITY_PAI_LESSTHAN20M_6430': "Moins de 20m²",
            'ACTIVITY_PAI_OVER20M_6440': "Plus de 20m²",
            'ACTIVITY_WAL_7000': "Cloisons / plafonds / combles",
            'ACTIVITY_WAL_PARTITIONS_7010': "Cloisons",
            'ACTIVITY_WAL_CEILINGS_7020': "Plafonds",
            'ACTIVITY_WAL_LOFT_7030': "Combles",
            'ACTIVITY_WAL_INSULATION_7040': "Isolation",
            'ACTIVITY_WAL_PLANNING_7050': "Aménagement",
            'ACTIVITY_WAL_PLANNINGANDINSULATION_7060': "Aménagement et isolation",
            'ACTIVITY_INS_8000': "Isolation",
            'ACTIVITY_INS_INTERIORINSULATION_8010': "Isolation thermique intérieure",
            'ACTIVITY_INS_EXTERNALTHERMALINSULATION_8020': "Isolation thermique extérieure",
            'ACTIVITY_INS_LOFTINSULATION_8030': "Isolation des combles",
            'ACTIVITY_INS_SOUNDPROOFING_8040': "Isolation phonique",
            'ACTIVITY_COU_9000': "Conseil, architecte et paysagiste",
            'ACTIVITY_COU_ARCHITECT_9010': "Architecte",
            'ACTIVITY_COU_DECORATIONINTERIORDESIGN_9020': "Décoration / aménagement d'intérieur",
            'ACTIVITY_COU_LANDSCAPER_9030': "Paysagiste",
            'ACTIVITY_KIT_10000': "Cuisine / Salle de Bain",
            'ACTIVITY_KIT_KITCHENROOM_10010': "Cuisine",
            'ACTIVITY_KIT_FULLKITCHEN_10020': "Cuisine complète",
            'ACTIVITY_KIT_KITCHENFURNITURE_10030': "Meubles de cuisines",
            'ACTIVITY_KIT_WORKPLAN_10040': "Plan de travail",
            'ACTIVITY_KIT_BATHROOM_10050': "Salle de bain",
            'ACTIVITY_KIT_BATHROOM_10060': "Salle de bain complète",
            'ACTIVITY_KIT_BATHROOMFURNITURE_10070': "Meubles de salle de bains",
            'ACTIVITY_ROO_11000': "Toiture / Charpente",
            'ACTIVITY_ROO_ROOFING_11010': "Toiture",
            'ACTIVITY_ROO_TERRACE_11020': "Terrasse",
            'ACTIVITY_ROO_TILE_11030': "Tuile",
            'ACTIVITY_ROO_SLATE_11040': "Ardoise",
            'ACTIVITY_ROO_ZINC_11050': "Zinc",
            'ACTIVITY_ROO_SHINGLE_11060': "Shingle",
            'ACTIVITY_ROO_SHEETMETAL_11070': "Tôle",
            'ACTIVITY_ROO_THATCH_11080': "Chaume",
            'ACTIVITY_ROO_WOODENROOFS_11090': "Charpente bois",
            'ACTIVITY_ROO_METALFRAME_11100': "Charpente métallique",
            'ACTIVITY_GAT_12000': "Portail / Porte de garage",
            'ACTIVITY_GAT_PORTAL_12010': "Portail",
            'ACTIVITY_GAT_PLASTICPVC_12020': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12030': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12040': "Bois",
            'ACTIVITY_GAT_ELECTRICGATE_12050': "Portail électrique",
            'ACTIVITY_GAT_PLASTICPVC_12060': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12070': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12080': "Bois",
            'ACTIVITY_GAT_GARAGEDOOR_12090': "Porte de garage",
            'ACTIVITY_GAT_PLASTICPVC_12100': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12110': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12120': "Bois",
            'ACTIVITY_GAT_ELECTRICGARAGEDOOR_12130': "Porte de garage électrique",
            'ACTIVITY_GAT_PLASTICPVC_12140': "Plastic / PVC",
            'ACTIVITY_GAT_METALALU_12150': "Métal / Alu",
            'ACTIVITY_GAT_WOOD_12160': "Bois",
            'ACTIVITY_GAR_13000': "Jardin / Terrase / Clôture",
            'ACTIVITY_GAR_GARDENANDGREENSPACES_13010': "Jardin et d'espaces verts",
            'ACTIVITY_GAR_WOODENDECK_13020': "Terrasse en bois",
            'ACTIVITY_GAR_FENCED_13030': "Clôture",
            'ACTIVITY_GAR_GRILLING_13040': "Grillage",
            'ACTIVITY_GAR_CANNISSE_13050': "Cannisse",
            'ACTIVITY_GAR_WOODPANELS_13060': "Panneaux bois",
            'ACTIVITY_GAR_PVCPANELS_13070': "Panneaux PVC",
            'ACTIVITY_GAR_WALLMURET_13080': "Mur / Muret",
            'ACTIVITY_GAR_CINDERBLOCK_13090': "Parpaing",
            'ACTIVITY_GAR_BRICK_13100': "Brique",
            'ACTIVITY_GAR_WOODFRAME_13110': "Ossature bois",
            'ACTIVITY_GAR_METAL_13120': "Métal",
            'ACTIVITY_GAR_EARTHWORK_13130': "Terrassement",
            'ACTIVITY_CON_14000': "Construction",
            'ACTIVITY_CON_HOUSE_14010': "Maison",
            'ACTIVITY_CON_TRADTIONNELLECONCRETEBLOCK_14020': "Tradtionnelle (parpaing)",
            'ACTIVITY_CON_INBRICK_14030': "En brique",
            'ACTIVITY_CON_WOODFRAME_14040': "Ossature bois",
            'ACTIVITY_CON_BBC_14050': "BBC",
            'ACTIVITY_CON_GARAGE_14060': "Garage",
            'ACTIVITY_CON_CONCRETE_14070': "Béton",
            'ACTIVITY_CON_BRICK_14080': "Brique",
            'ACTIVITY_CON_WOODFRAME_14090': "Ossature bois",
            'ACTIVITY_CON_METAL_14100': "Métal",
            'ACTIVITY_CON_HOUSEEXTENSION_14110': "Extension de maison",
            'ACTIVITY_CON_CINDERBLOCK_14120': "Parpaing",
            'ACTIVITY_CON_BRICK_14130': "Brique",
            'ACTIVITY_CON_WOODFRAME_14140': "Ossature bois",
            'ACTIVITY_CON_FOUNDATIONS_14150': "Fondations",
            'ACTIVITY_CON_SWIMMINGPOOL_14160': "Piscine"
        });
    }])
;
