angular.module('Yaka')
    .config(['cloudinaryProvider', function (cloudinaryProvider) {
        cloudinaryProvider
            .set("cloud_name", "yaka")
            .set("upload_preset", "cxsdlf5n");
    }])
    .config(['uiGmapGoogleMapApiProvider', function (GoogleMapApi) {
        GoogleMapApi.configure({
            key: 'AIzaSyDtq1oFK_ku6rSm9OHM8Q0MlHeOYzOWgr8',
            libraries: 'weather,geometry,visualization'
            // v: '3.20',
        });
    }])
    .config(['$translateProvider', function (translateProvider) {
        // Simply register translation table as object hash
        translateProvider.useSanitizeValueStrategy('escape');
        translateProvider.translations('fr', {
            'ACTIVITY_OTHER': "Autre - Je ne sais pas",
            'ACTIVITY_ELECTRICITY': "Électricité",
            'ACTIVITY_PLUMBING': "Plomberie",
            'ACTIVITY_HEATING_AIRCONDITIONING': "Chauffage climatisation",
            'ACTIVITY_CARPENTRY_WINDOW_VERANDA': "Menuiserie window veranda",
            'ACTIVITY_LOCKSMITH': "Serrurerie",
            'ACTIVITY_PAINTING_WALLS_FLOORS': "Peinture, murs et sols",
            'ACTIVITY_WALLS_CEILING_ROOFS': "Cloisons plafonds combles",
            'ACTIVITY_ISOLATION': "Isolation",
            'ACTIVITY_COUNCIL_ARCHI_LANDSCAPE': "Conseil architecte paysagiste",
            'ACTIVITY_KITCHEN_BATHROOM': "Cuisine salle-de-bain",
            'ACTIVITY_ROOFING_CARPENTRY': "Toiture charpente",
            'ACTIVITY_PORTAL_GARAGE': "Garage portail",
            'ACTIVITY_GARDEN_TERRACE_FENCE': "Jardin terrase clôture",
            'ACTIVITY_CONSTRUCTION': "Construction",
            'ACTIVITY_EL_PLUG_CABLE': "Prise / cablage",
            'ACTIVITY_EL_LIGHTING': "Éclairage",
            'ACTIVITY_EL_LIGHTING_INSIDE': "À l'intérieur",
            'ACTIVITY_EL_LIGHTING_EXTERIOR': "Extérieur",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER': "Radiatior sèche-serviettes",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR': "Radiatior",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER': "Sèche-serviettes",
            'ACTIVITY_EL_BOILER_WATER_HEATER': "Chaudière chauffe-eau",
            'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER': "Chaudière",
            'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER': "Chauffe-eau",
            'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK': "Ballon d'eau chaude",
            'ACTIVITY_EL_SWITCHBOARD': "Tableau électrique",
            'ACTIVITY_EL_ELECTRICMETER': "Compteur électrique",
            'ACTIVITY_EL_AUTOMATION': "Domotique",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM': "Sécurité alarm interphone",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS': "Alarmes",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY': "Vidéo surveillance",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM': "Interphone",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD': "Clavier",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR': "Détecteur de fumée",
            'ACTIVITY_PL_TOILETS': "Toilettes",
            'ACTIVITY_PL_TOILETS_CLASSIC': "Classique",
            'ACTIVITY_PL_TOILETS_SUSPENDED': "Suspendu",
            'ACTIVITY_PL_TOILETS_MECHANISM': "Mécanisme",
            'ACTIVITY_PL_SHOWER': "Douche",
            'ACTIVITY_PL_SHOWER_SHOWER': "Douche",
            'ACTIVITY_PL_SHOWER_CABIN': "Cabine",
            'ACTIVITY_PL_SHOWER_COLUMN': "Colonne",
            'ACTIVITY_PL_SHOWER_DOOR': "Porte",
            'ACTIVITY_PL_SHOWER_GLASS': "Pare-douche",
            'ACTIVITY_PL_BATHTUBE': "Baignoire",
            'ACTIVITY_PL_BATHTUBE_BATH': "Baignoire",
            'ACTIVITY_PL_BATHTUBE_TAP_FAUCET': "Robinet / mitigeur",
            'ACTIVITY_PL_BATHTUBE_GLASS': "Pare-baignoire",
            'ACTIVITY_PL_BASIN_SINK': "Lavabo / evier",
            'ACTIVITY_PL_PIPING_CANALIZATION': "Tuyauterie canalisation",
            'ACTIVITY_PL_BOILER_WATER_HEATER': "Chaudière chauffe-eau",
            'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER': "Chaudière",
            'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER': "Chauffe-eau",
            'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK': "Reservoir d'eau chaude",
            'ACTIVITY_PL_SOFTENER': "Adoucisseur",
            'ACTIVITY_HE_BOILER_WATER_HEATER': "Chaudière chauffe-eau",
            'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER': "Chaudière",
            'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER': "Chauffe-eau",
            'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK': "Reservoir d'eau chaude",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER': "Radiateur / Sèche-serviettes",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR': "Radiateur",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER': "Sèche-serviettes",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER': "Chauffage électrique",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER': "Chauffage à gaz",
            'ACTIVITY_HE_FLOOR_HEATING': "Chauffage au sol",
            'ACTIVITY_HE_THERMOSTAT': "Thermostat",
            'ACTIVITY_HE_AIR_CONDITIONER': "Climatisation",
            'ACTIVITY_HE_HEAT_PUMP': "Pompe à chaleur",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE': "Poele insert cheminee",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE': "Poêle à bois",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE': "Poêle à granulés",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE': "Cheminée",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT': "Inser",
            'ACTIVITY_HE_VMC_VMC': "Vmc",
            'ACTIVITY_HE_VMC_SINGLE_FLOW': "Simple flux",
            'ACTIVITY_HE_VMC_DOUBLE_FLOW': "Double flux",
            'ACTIVITY_CA_SINGLE_DOOR': "Porte simple",
            'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM': "Aluminium",
            'ACTIVITY_CA_SINGLE_DOOR_WOOD': "Bois",
            'ACTIVITY_CA_SINGLE_DOOR_PVC': "Pvc",
            'ACTIVITY_CA_REINFORCED_DOOR': "Porte blindée",
            'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM': "Aluminium",
            'ACTIVITY_CA_REINFORCED_DOOR_WOOD': "Bois",
            'ACTIVITY_CA_REINFORCED_DOOR_PVC': "Pvc",
            'ACTIVITY_CA_WINDOW_DOORWINDOW': "Fenêtre / Porte-fenêtre",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT': "Fenêtre de toit / Velux",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW': "Fenêtre",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW': "Porte-fenêtre",
            'ACTIVITY_CA_SHUTTERS': "Volets",
            'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS': "Volet élecrique roulant",
            'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS': "Volet roulant manuel",
            'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS': "Volet à battant",
            'ACTIVITY_CA_STAIRCASE': "Escalier",
            'ACTIVITY_CA_MEZZANINE': "Mezzanine",
            'ACTIVITY_CA_CLOSETS_CUPBOARDS': "Placards / rangements",
            'ACTIVITY_CA_VERANDA': "Véranda",
            'ACTIVITY_LO_SINGLE_DOOR': "Porte simple",
            'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM': "Aluminium",
            'ACTIVITY_LO_SINGLE_DOOR_WOOD': "Bois",
            'ACTIVITY_LO_SINGLE_DOOR_PVC': "Pvc",
            'ACTIVITY_LO_REINFORCED_DOOR': "Porte blindée",
            'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM': "Aluminium",
            'ACTIVITY_LO_REINFORCED_DOOR_WOOD': "Bois",
            'ACTIVITY_LO_REINFORCED_DOOR_PVC': "Pvc",
            'ACTIVITY_LO_CLASSIC_LOCK': "Serrure classique",
            'ACTIVITY_LO_MULTIPOINT_LOCK': "Serrure multi-points",
            'ACTIVITY_LO_ELECTRIC_GACHE': "Gache électrique",
            'ACTIVITY_LO_SHUTTERS': "Volets roulants",
            'ACTIVITY_LO_METALLIC_CURTAINS': "Rideaux métallique",
            'ACTIVITY_PA_PAINT_AND_COATINGS': "Peinture et enduits",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT': "Peinture intérieur",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS': "Enduit décoratif",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING': "Exterieur peinture",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS': "Exterieur coatings",
            'ACTIVITY_PA_WALL_PAPER': "Papier peint",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE': "Sol intérieur",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET': "Carrelage",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET': "Parquet",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR': "Moquette",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE': "Sol plastique",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE': "Pierre",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE': "Béton",
            'ACTIVITY_PA_OUTDOOR FLOOR': "Sol extérieur",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE': "Carrelage",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE': "Pierre",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE': "Béton",
            'ACTIVITY_WA_BULKHEAD': "Cloisons",
            'ACTIVITY_WA_CEILINGS': "Plafonds",
            'ACTIVITY_WA_ATTIC': "Combles",
            'ACTIVITY_WA_ATTIC_INSULATION': "Isolation",
            'ACTIVITY_WA_ATTIC_ADJUSTING': "Aménagement",
            'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING': "Aménagement et isolation",
            'ACTIVITY_IS_INTERIOR_THERMIC': "Thermique intérieur",
            'ACTIVITY_IS_EXTERIOR_THERMIC': "Thermique extérieur",
            'ACTIVITY_IS_ATTIC': "Combles",
            'ACTIVITY_IS_SOUNDPROOFING': "Insonorisation",
            'ACTIVITY_CO_ARCHITECT': "Architecte",
            'ACTIVITY_CO_INTERIOR_DESIGNER': "Décorateur d'intérieur",
            'ACTIVITY_CO_DECORATION_INTERIOR_AMENAGMENT': "Décoration / Aménagement d'intérieur",
            'ACTIVITY_CO_LANDSCAPER': "Paysagiste",
            'ACTIVITY_KI_FULL_KITCHEN': "Cuisine complète",
            'ACTIVITY_KI_KITCHEN_FURNITURE': "Meuble de cuisine",
            'ACTIVITY_KI_WORKPLAN_KITCHEN': "Plan de travail pour cuisine",
            'ACTIVITY_KI_BATHROOM': "Salle de bains",
            'ACTIVITY_KI_BATHROOM_FURNITURE': "Meubles de salle de bains",
            'ACTIVITY_RO_ROOFING': "Toiture",
            'ACTIVITY_RO_ROOFING_TILES': "Tuile",
            'ACTIVITY_RO_ROOFING_SLATE': "Ardoise",
            'ACTIVITY_RO_ROOFING_ZINC': "Zinc",
            'ACTIVITY_RO_ROOFING_SHINGLE': "Shingle",
            'ACTIVITY_RO_ROOFING_SHEET_METAL': "Tôle",
            'ACTIVITY_RO_ROOFING_CHAUME': "Chaume",
            'ACTIVITY_RO_ROOFING_TERRASSE': "Terrasse",
            'ACTIVITY_RO_WOODEN_ROOFS': "Charpente bois",
            'ACTIVITY_RO_METAL_FRAME': "Charpente métallique",
            'ACTIVITY_PO_WOODEN_PORTAL': "Portail : bois",
            'ACTIVITY_PO_ALUMINUM_METAL_PORTAL': "Portail : métal/Alu",
            'ACTIVITY_PO_PVC PORTAL': "Portail : platique/PVC",
            'ACTIVITY_PO_WOODEN_GARAGE_DOOR': "Porte de garage : bois",
            'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR': "Porte de garage : métal/Alu",
            'ACTIVITY_PO_PVC_GARAGE_DOOR': "Porte de garage : platique/PVC",
            'ACTIVITY_GA_GARDEN_GREEN_SPACES': "Espaces verts jardin",
            'ACTIVITY_GA_WOODEN_DECK': "Terrasse en bois",
            'ACTIVITY_GA_FENCED': "Clôture",
            'ACTIVITY_GA_FENCED_GRILLING': "Grillage",
            'ACTIVITY_GA_FENCED_CANNISSE': "Cannisse",
            'ACTIVITY_GA_FENCED_WOOD_PANELS': "Panneaux bois",
            'ACTIVITY_GA_FENCED_PVC_PANELS': "Panneaux pvc",
            'ACTIVITY_GA_WALL_DYKE': "Mur / muret",
            'ACTIVITY_GA_EARTHWORK': "Terrassement",
            'ACTIVITY_CO_HOUSE': "Maison",
            'ACTIVITY_CO_HOUSE_CLASSIC': "Classique (parpaing)",
            'ACTIVITY_CO_HOUSE_BRICK': "Brique",
            'ACTIVITY_CO_HOUSE_WOOD_FRAME': "Ossature bois",
            'ACTIVITY_CO_HOUSE_BBC': "Bbc",
            'ACTIVITY_CO_GARAGE': "Garage",
            'ACTIVITY_CO_GARAGE_CONCRETE': "Béton",
            'ACTIVITY_CO_GARAGE_METAL': "Métal",
            'ACTIVITY_CO_GARAGE_BRICK': "Brique",
            'ACTIVITY_CO_GARAGE_WOOD_FRAME': "Ossature bois",
            'ACTIVITY_CO_HOUSE_EXTENSION': "Extension de maison",
            'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK': "Classique (parpaing)",
            'ACTIVITY_CO_HOUSE_EXTENSION_BRICK': "Brique",
            'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME': "Cadre en bois",
            'ACTIVITY_CO_FOUNDATIONS': "Fondations",
            'ACTIVITY_CO_SWIMMING POOL': "Piscine",
            'ACTIVITY_EL_PLUG_CABLE_INSTALLATION': "Installation",
            'ACTIVITY_EL_LIGHTING_INSIDE_INSTALLATION': "Installation",
            'ACTIVITY_EL_LIGHTING_EXTERIOR_INSTALLATION': "Installation",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_INSTALLATION': "Installation",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_INSTALLATION': "Installation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_INSTALLATION': "Installation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_INSTALLATION': "Installation",
            'ACTIVITY_EL_SWITCHBOARD_INSTALLATION': "Installation",
            'ACTIVITY_EL_ELECTRICMETER_INSTALLATION': "Installation",
            'ACTIVITY_EL_AUTOMATION_INSTALLATION': "Installation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_INSTALLATION': "Installation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_INSTALLATION': "Installation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_INSTALLATION': "Installation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_INSTALLATION': "Installation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_INSTALLATION': "Installation",
            'ACTIVITY_PL_TOILETS_CLASSIC_INSTALLATION': "Installation",
            'ACTIVITY_PL_TOILETS_SUSPENDED_INSTALLATION': "Installation",
            'ACTIVITY_PL_TOILETS_MECHANISM_INSTALLATION': "Installation",
            'ACTIVITY_PL_SHOWER_SHOWER_INSTALLATION': "Installation",
            'ACTIVITY_PL_SHOWER_CABIN_INSTALLATION': "Installation",
            'ACTIVITY_PL_SHOWER_COLUMN_INSTALLATION': "Installation",
            'ACTIVITY_PL_SHOWER_DOOR_INSTALLATION': "Installation",
            'ACTIVITY_PL_SHOWER_GLASS_INSTALLATION': "Installation",
            'ACTIVITY_PL_BATHTUBE_BATH_INSTALLATION': "Installation",
            'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_INSTALLATION': "Installation",
            'ACTIVITY_PL_BATHTUBE_GLASS_INSTALLATION': "Installation",
            'ACTIVITY_PL_BASIN_SINK_INSTALLATION': "Installation",
            'ACTIVITY_PL_PIPING_CANALIZATION_INSTALLATION': "Installation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_INSTALLATION': "Installation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_INSTALLATION': "Installation",
            'ACTIVITY_PL_SOFTENER_INSTALLATION': "Installation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_INSTALLATION': "Installation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_INSTALLATION': "Installation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_INSTALLATION': "Installation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_INSTALLATION': "Installation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_INSTALLATION': "Installation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_INSTALLATION': "Installation",
            'ACTIVITY_HE_FLOOR_HEATING_INSTALLATION': "Installation",
            'ACTIVITY_HE_THERMOSTAT_INSTALLATION': "Installation",
            'ACTIVITY_HE_AIR_CONDITIONER_INSTALLATION': "Installation",
            'ACTIVITY_HE_HEAT_PUMP_INSTALLATION': "Installation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_INSTALLATION': "Installation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_INSTALLATION': "Installation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_INSTALLATION': "Installation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_INSTALLATION': "Installation",
            'ACTIVITY_HE_VMC_SINGLE_FLOW_INSTALLATION': "Installation",
            'ACTIVITY_HE_VMC_DOUBLE_FLOW_INSTALLATION': "Installation",
            'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_INSTALLATION': "Installation",
            'ACTIVITY_CA_SINGLE_DOOR_WOOD_INSTALLATION': "Installation",
            'ACTIVITY_CA_SINGLE_DOOR_PVC_INSTALLATION': "Installation",
            'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_INSTALLATION': "Installation",
            'ACTIVITY_CA_REINFORCED_DOOR_WOOD_INSTALLATION': "Installation",
            'ACTIVITY_CA_REINFORCED_DOOR_PVC_INSTALLATION': "Installation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_INSTALLATION': "Installation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_INSTALLATION': "Installation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_INSTALLATION': "Installation",
            'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_INSTALLATION': "Installation",
            'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_INSTALLATION': "Installation",
            'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_INSTALLATION': "Installation",
            'ACTIVITY_CA_STAIRCASE_INSTALLATION': "Installation",
            'ACTIVITY_CA_MEZZANINE_INSTALLATION': "Installation",
            'ACTIVITY_CA_CLOSETS_CUPBOARDS_INSTALLATION': "Installation",
            'ACTIVITY_CA_VERANDA_INSTALLATION': "Installation",
            'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_INSTALLATION': "Installation",
            'ACTIVITY_LO_SINGLE_DOOR_WOOD_INSTALLATION': "Installation",
            'ACTIVITY_LO_SINGLE_DOOR_PVC_INSTALLATION': "Installation",
            'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_INSTALLATION': "Installation",
            'ACTIVITY_LO_REINFORCED_DOOR_WOOD_INSTALLATION': "Installation",
            'ACTIVITY_LO_REINFORCED_DOOR_PVC_INSTALLATION': "Installation",
            'ACTIVITY_LO_CLASSIC_LOCK_INSTALLATION': "Installation",
            'ACTIVITY_LO_MULTIPOINT_LOCK_INSTALLATION': "Installation",
            'ACTIVITY_LO_ELECTRIC_GACHE_INSTALLATION': "Installation",
            'ACTIVITY_LO_SHUTTERS_INSTALLATION': "Installation",
            'ACTIVITY_LO_METALLIC_CURTAINS_INSTALLATION': "Installation",
            'ACTIVITY_WA_BULKHEAD_INSTALLATION': "Installation",
            'ACTIVITY_WA_CEILINGS_INSTALLATION': "Installation",
            'ACTIVITY_WA_ATTIC_INSULATION_INSTALLATION': "Installation",
            'ACTIVITY_WA_ATTIC_ADJUSTING_INSTALLATION': "Installation",
            'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING_INSTALLATION': "Installation",
            'ACTIVITY_IS_INTERIOR_THERMIC_INSTALLATION': "Installation",
            'ACTIVITY_IS_EXTERIOR_THERMIC_INSTALLATION': "Installation",
            'ACTIVITY_IS_ATTIC_INSTALLATION': "Installation",
            'ACTIVITY_IS_SOUNDPROOFING_INSTALLATION': "Installation",
            'ACTIVITY_KI_FULL_KITCHEN_INSTALLATION': "Installation",
            'ACTIVITY_KI_KITCHEN_FURNITURE_INSTALLATION': "Installation",
            'ACTIVITY_KI_WORKPLAN_KITCHEN_INSTALLATION': "Installation",
            'ACTIVITY_KI_BATHROOM_INSTALLATION': "Installation",
            'ACTIVITY_KI_BATHROOM_FURNITURE_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_TILES_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_SLATE_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_ZINC_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_SHINGLE_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_SHEET_METAL_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_CHAUME_INSTALLATION': "Installation",
            'ACTIVITY_RO_ROOFING_TERRASSE_INSTALLATION': "Installation",
            'ACTIVITY_RO_WOODEN_ROOFS_INSTALLATION': "Installation",
            'ACTIVITY_RO_METAL_FRAME_INSTALLATION': "Installation",
            'ACTIVITY_PO_WOODEN_PORTAL_INSTALLATION': "Installation",
            'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_INSTALLATION': "Installation",
            'ACTIVITY_PO_PVC PORTAL_INSTALLATION': "Installation",
            'ACTIVITY_PO_WOODEN_GARAGE_DOOR_INSTALLATION': "Installation",
            'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_INSTALLATION': "Installation",
            'ACTIVITY_PO_PVC_GARAGE_DOOR_INSTALLATION': "Installation",
            'ACTIVITY_GA_GARDEN_GREEN_SPACES_INSTALLATION': "Installation",
            'ACTIVITY_GA_WOODEN_DECK_INSTALLATION': "Installation",
            'ACTIVITY_GA_FENCED_GRILLING_INSTALLATION': "Installation",
            'ACTIVITY_GA_FENCED_CANNISSE_INSTALLATION': "Installation",
            'ACTIVITY_GA_FENCED_WOOD_PANELS_INSTALLATION': "Installation",
            'ACTIVITY_GA_FENCED_PVC_PANELS_INSTALLATION': "Installation",
            'ACTIVITY_GA_WALL_DYKE_INSTALLATION': "Installation",
            'ACTIVITY_EL_PLUG_CABLE_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_LIGHTING_INSIDE_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_LIGHTING_EXTERIOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SWITCHBOARD_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_ELECTRICMETER_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_TOILETS_CLASSIC_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_TOILETS_SUSPENDED_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_TOILETS_MECHANISM_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SHOWER_SHOWER_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SHOWER_CABIN_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SHOWER_COLUMN_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SHOWER_DOOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SHOWER_GLASS_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BATHTUBE_BATH_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BATHTUBE_GLASS_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BASIN_SINK_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_PIPING_CANALIZATION_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_REPLACEMENT': "Remplacement",
            'ACTIVITY_PL_SOFTENER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_FLOOR_HEATING_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_THERMOSTAT_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_AIR_CONDITIONER_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_HEAT_PUMP_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_VMC_SINGLE_FLOW_REPLACEMENT': "Remplacement",
            'ACTIVITY_HE_VMC_DOUBLE_FLOW_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SINGLE_DOOR_WOOD_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SINGLE_DOOR_PVC_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_REINFORCED_DOOR_WOOD_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_REINFORCED_DOOR_PVC_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_STAIRCASE_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_MEZZANINE_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_CLOSETS_CUPBOARDS_REPLACEMENT': "Remplacement",
            'ACTIVITY_CA_VERANDA_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_SINGLE_DOOR_WOOD_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_SINGLE_DOOR_PVC_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_REINFORCED_DOOR_WOOD_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_REINFORCED_DOOR_PVC_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_CLASSIC_LOCK_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_MULTIPOINT_LOCK_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_ELECTRIC_GACHE_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_SHUTTERS_REPLACEMENT': "Remplacement",
            'ACTIVITY_LO_METALLIC_CURTAINS_REPLACEMENT': "Remplacement",
            'ACTIVITY_WA_BULKHEAD_REPLACEMENT': "Remplacement",
            'ACTIVITY_WA_CEILINGS_REPLACEMENT': "Remplacement",
            'ACTIVITY_WA_ATTIC_INSULATION_REPLACEMENT': "Remplacement",
            'ACTIVITY_WA_ATTIC_ADJUSTING_REPLACEMENT': "Remplacement",
            'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING_REPLACEMENT': "Remplacement",
            'ACTIVITY_IS_INTERIOR_THERMIC_REPLACEMENT': "Remplacement",
            'ACTIVITY_IS_EXTERIOR_THERMIC_REPLACEMENT': "Remplacement",
            'ACTIVITY_IS_ATTIC_REPLACEMENT': "Remplacement",
            'ACTIVITY_IS_SOUNDPROOFING_REPLACEMENT': "Remplacement",
            'ACTIVITY_KI_FULL_KITCHEN_REPLACEMENT': "Remplacement",
            'ACTIVITY_KI_KITCHEN_FURNITURE_REPLACEMENT': "Remplacement",
            'ACTIVITY_KI_WORKPLAN_KITCHEN_REPLACEMENT': "Remplacement",
            'ACTIVITY_KI_BATHROOM_REPLACEMENT': "Remplacement",
            'ACTIVITY_KI_BATHROOM_FURNITURE_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_TILES_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_SLATE_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_ZINC_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_SHINGLE_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_SHEET_METAL_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_CHAUME_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_ROOFING_TERRASSE_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_WOODEN_ROOFS_REPLACEMENT': "Remplacement",
            'ACTIVITY_RO_METAL_FRAME_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_WOODEN_PORTAL_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_PVC PORTAL_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_WOODEN_GARAGE_DOOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_PO_PVC_GARAGE_DOOR_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_GARDEN_GREEN_SPACES_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_WOODEN_DECK_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_FENCED_GRILLING_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_FENCED_CANNISSE_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_FENCED_WOOD_PANELS_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_FENCED_PVC_PANELS_REPLACEMENT': "Remplacement",
            'ACTIVITY_GA_WALL_DYKE_REPLACEMENT': "Remplacement",
            'ACTIVITY_EL_PLUG_CABLE_REPAIR': "réparation",
            'ACTIVITY_EL_LIGHTING_INSIDE_REPAIR': "réparation",
            'ACTIVITY_EL_LIGHTING_EXTERIOR_REPAIR': "réparation",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_REPAIR': "réparation",
            'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPAIR': "réparation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_REPAIR': "réparation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_REPAIR': "réparation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_REPAIR': "réparation",
            'ACTIVITY_EL_SWITCHBOARD_REPAIR': "réparation",
            'ACTIVITY_EL_ELECTRICMETER_REPAIR': "réparation",
            'ACTIVITY_EL_AUTOMATION_REPAIR': "réparation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_REPAIR': "réparation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_REPAIR': "réparation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_REPAIR': "réparation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_REPAIR': "réparation",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_REPAIR': "réparation",
            'ACTIVITY_PL_TOILETS_CLASSIC_REPAIR': "réparation",
            'ACTIVITY_PL_TOILETS_SUSPENDED_REPAIR': "réparation",
            'ACTIVITY_PL_TOILETS_MECHANISM_REPAIR': "réparation",
            'ACTIVITY_PL_SHOWER_SHOWER_REPAIR': "réparation",
            'ACTIVITY_PL_SHOWER_CABIN_REPAIR': "réparation",
            'ACTIVITY_PL_SHOWER_COLUMN_REPAIR': "réparation",
            'ACTIVITY_PL_SHOWER_DOOR_REPAIR': "réparation",
            'ACTIVITY_PL_SHOWER_GLASS_REPAIR': "réparation",
            'ACTIVITY_PL_BATHTUBE_BATH_REPAIR': "réparation",
            'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_REPAIR': "réparation",
            'ACTIVITY_PL_BATHTUBE_GLASS_REPAIR': "réparation",
            'ACTIVITY_PL_BASIN_SINK_REPAIR': "réparation",
            'ACTIVITY_PL_PIPING_CANALIZATION_REPAIR': "réparation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_REPAIR': "réparation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_REPAIR': "réparation",
            'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_REPAIR': "réparation",
            'ACTIVITY_PL_SOFTENER_REPAIR': "réparation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_REPAIR': "réparation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_REPAIR': "réparation",
            'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_REPAIR': "réparation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_REPAIR': "réparation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPAIR': "réparation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_REPAIR': "réparation",
            'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_REPAIR': "réparation",
            'ACTIVITY_HE_FLOOR_HEATING_REPAIR': "réparation",
            'ACTIVITY_HE_THERMOSTAT_REPAIR': "réparation",
            'ACTIVITY_HE_AIR_CONDITIONER_REPAIR': "réparation",
            'ACTIVITY_HE_HEAT_PUMP_REPAIR': "réparation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_REPAIR': "réparation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_REPAIR': "réparation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_REPAIR': "réparation",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_REPAIR': "réparation",
            'ACTIVITY_HE_VMC_SINGLE_FLOW_REPAIR': "réparation",
            'ACTIVITY_HE_VMC_DOUBLE_FLOW_REPAIR': "réparation",
            'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_REPAIR': "réparation",
            'ACTIVITY_CA_SINGLE_DOOR_WOOD_REPAIR': "réparation",
            'ACTIVITY_CA_SINGLE_DOOR_PVC_REPAIR': "réparation",
            'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_REPAIR': "réparation",
            'ACTIVITY_CA_REINFORCED_DOOR_WOOD_REPAIR': "réparation",
            'ACTIVITY_CA_REINFORCED_DOOR_PVC_REPAIR': "réparation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_REPAIR': "réparation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_REPAIR': "réparation",
            'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_REPAIR': "réparation",
            'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_REPAIR': "réparation",
            'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_REPAIR': "réparation",
            'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_REPAIR': "réparation",
            'ACTIVITY_CA_STAIRCASE_REPAIR': "réparation",
            'ACTIVITY_CA_MEZZANINE_REPAIR': "réparation",
            'ACTIVITY_CA_CLOSETS_CUPBOARDS_REPAIR': "réparation",
            'ACTIVITY_CA_VERANDA_REPAIR': "réparation",
            'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_REPAIR': "réparation",
            'ACTIVITY_LO_SINGLE_DOOR_WOOD_REPAIR': "réparation",
            'ACTIVITY_LO_SINGLE_DOOR_PVC_REPAIR': "réparation",
            'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_REPAIR': "réparation",
            'ACTIVITY_LO_REINFORCED_DOOR_WOOD_REPAIR': "réparation",
            'ACTIVITY_LO_REINFORCED_DOOR_PVC_REPAIR': "réparation",
            'ACTIVITY_LO_CLASSIC_LOCK_REPAIR': "réparation",
            'ACTIVITY_LO_MULTIPOINT_LOCK_REPAIR': "réparation",
            'ACTIVITY_LO_ELECTRIC_GACHE_REPAIR': "réparation",
            'ACTIVITY_LO_SHUTTERS_REPAIR': "réparation",
            'ACTIVITY_LO_METALLIC_CURTAINS_REPAIR': "réparation",
            'ACTIVITY_WA_BULKHEAD_REPAIR': "réparation",
            'ACTIVITY_WA_CEILINGS_REPAIR': "réparation",
            'ACTIVITY_WA_ATTIC_INSULATION_REPAIR': "réparation",
            'ACTIVITY_IS_INTERIOR_THERMIC_REPAIR': "réparation",
            'ACTIVITY_IS_EXTERIOR_THERMIC_REPAIR': "réparation",
            'ACTIVITY_IS_ATTIC_REPAIR': "réparation",
            'ACTIVITY_IS_SOUNDPROOFING_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_TILES_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_SLATE_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_ZINC_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_SHINGLE_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_SHEET_METAL_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_CHAUME_REPAIR': "réparation",
            'ACTIVITY_RO_ROOFING_TERRASSE_REPAIR': "réparation",
            'ACTIVITY_RO_WOODEN_ROOFS_REPAIR': "réparation",
            'ACTIVITY_RO_METAL_FRAME_REPAIR': "réparation",
            'ACTIVITY_PO_WOODEN_PORTAL_REPAIR': "réparation",
            'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_REPAIR': "réparation",
            'ACTIVITY_PO_PVC PORTAL_REPAIR': "réparation",
            'ACTIVITY_PO_WOODEN_GARAGE_DOOR_REPAIR': "réparation",
            'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_REPAIR': "réparation",
            'ACTIVITY_PO_PVC_GARAGE_DOOR_REPAIR': "réparation",
            'ACTIVITY_GA_GARDEN_GREEN_SPACES_REPAIR': "réparation",
            'ACTIVITY_GA_WOODEN_DECK_REPAIR': "réparation",
            'ACTIVITY_GA_FENCED_GRILLING_REPAIR': "réparation",
            'ACTIVITY_GA_FENCED_CANNISSE_REPAIR': "réparation",
            'ACTIVITY_GA_FENCED_WOOD_PANELS_REPAIR': "réparation",
            'ACTIVITY_GA_FENCED_PVC_PANELS_REPAIR': "réparation",
            'ACTIVITY_GA_WALL_DYKE_REPAIR': "réparation",
            'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Entretien",
            'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_MAINTENANCE': "Entretien",
            'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_MAINTENANCE': "Entretien",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_MAINTENANCE': "Entretien",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_MAINTENANCE': "Entretien",
            'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_MAINTENANCE': "Entretien",
            'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Entretien",
            'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_MAINTENANCE': "Entretien",
            'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_MAINTENANCE': "Entretien",
            'ACTIVITY_PL_SOFTENER_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_AIR_CONDITIONER_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_MAINTENANCE': "Entretien",
            'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_TILES_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_SLATE_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_ZINC_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_SHINGLE_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_SHEET_METAL_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_CHAUME_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_ROOFING_TERRASSE_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_WOODEN_ROOFS_MAINTENANCE': "Entretien",
            'ACTIVITY_RO_METAL_FRAME_MAINTENANCE': "Entretien",
            'ACTIVITY_KI_FULL_KITCHEN_CREATION': "Création",
            'ACTIVITY_KI_BATHROOM_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_CLASSIC_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_BRICK_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_WOOD_FRAME_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_BBC_CREATION': "Création",
            'ACTIVITY_CO_GARAGE_CONCRETE_CREATION': "Création",
            'ACTIVITY_CO_GARAGE_METAL_CREATION': "Création",
            'ACTIVITY_CO_GARAGE_BRICK_CREATION': "Création",
            'ACTIVITY_CO_GARAGE_WOOD_FRAME_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_EXTENSION_BRICK_CREATION': "Création",
            'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME_CREATION': "Création",
            'ACTIVITY_CO_FOUNDATIONS_CREATION': "Création",
            'ACTIVITY_CO_SWIMMING POOL_CREATION': "Création",
            'ACTIVITY_CA_SINGLE_DOOR_WOOD_RENOVATION': "Rénovation",
            'ACTIVITY_CA_REINFORCED_DOOR_WOOD_RENOVATION': "Rénovation",
            'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_RENOVATION': "Rénovation",
            'ACTIVITY_GA_GARDEN_GREEN_SPACES_RENOVATION': "Rénovation",
            'ACTIVITY_GA_WOODEN_DECK_RENOVATION': "Rénovation",
            'ACTIVITY_GA_FENCED_WOOD_PANELS_RENOVATION': "Rénovation",
            'ACTIVITY_GA_WALL_DYKE_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_CLASSIC_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_BRICK_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_WOOD_FRAME_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_BBC_RENOVATION': "Rénovation",
            'ACTIVITY_CO_GARAGE_CONCRETE_RENOVATION': "Rénovation",
            'ACTIVITY_CO_GARAGE_METAL_RENOVATION': "Rénovation",
            'ACTIVITY_CO_GARAGE_BRICK_RENOVATION': "Rénovation",
            'ACTIVITY_CO_GARAGE_WOOD_FRAME_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_EXTENSION_BRICK_RENOVATION': "Rénovation",
            'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME_RENOVATION': "Rénovation",
            'ACTIVITY_CO_FOUNDATIONS_RENOVATION': "Rénovation",
            'ACTIVITY_CO_SWIMMING POOL_RENOVATION': "Rénovation",
            'ACTIVITY_PL_TOILETS_CLASSIC_UNCORK': "Déboucher",
            'ACTIVITY_PL_TOILETS_SUSPENDED_UNCORK': "Déboucher",
            'ACTIVITY_PL_SHOWER_SHOWER_UNCORK': "Déboucher",
            'ACTIVITY_PL_BATHTUBE_BATH_UNCORK': "Déboucher",
            'ACTIVITY_PL_BASIN_SINK_UNCORK': "Déboucher",
            'ACTIVITY_PL_PIPING_CANALIZATION_UNCORK': "Déboucher",
            'ACTIVITY_LO_METALLIC_CURTAINS_L30M2': "Moins de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_L30M2': "Moins de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_L30M2': "Moins de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_L30M2': "Moins de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_L30M2': "Moins de 30m²",
            'ACTIVITY_PA_WALL_PAPER_L30M2': "Moins de 30m²",
            'ACTIVITY_LO_METALLIC_CURTAINS_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_WALL_PAPER_O30M2': "Plus de 30m²",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_L20M2': "Moins de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_O20M2': "Plus de 20m²",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_O20M2': "Plus de 20m²",
            'ACTIVITY_LO_METALLIC_CURTAINS_GOOD': "Bon état",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_GOOD': "Bon état",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_GOOD': "Bon état",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_GOOD': "Bon état",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_GOOD': "Bon état",
            'ACTIVITY_PA_WALL_PAPER_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_GOOD': "Bon état",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_GOOD': "Bon état",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_GOOD': "Bon état",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_GOOD': "Bon état",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_GOOD': "Bon état",
            'ACTIVITY_LO_METALLIC_CURTAINS_MIDDLE': "État moyen",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_MIDDLE': "État moyen",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_MIDDLE': "État moyen",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_MIDDLE': "État moyen",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_MIDDLE': "État moyen",
            'ACTIVITY_PA_WALL_PAPER_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_MIDDLE': "État moyen",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_MIDDLE': "État moyen",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_MIDDLE': "État moyen",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_MIDDLE': "État moyen",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_MIDDLE': "État moyen",
            'ACTIVITY_LO_METALLIC_CURTAINS_BAD': "Mauvais éat",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_BAD': "Mauvais éat",
            'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_BAD': "Mauvais éat",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_BAD': "Mauvais éat",
            'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_BAD': "Mauvais éat",
            'ACTIVITY_PA_WALL_PAPER_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_CARPET_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_BAD': "Mauvais éat",
            'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_BAD': "Mauvais éat",
            'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_BAD': "Mauvais éat",
            'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_BAD': "Mauvais éat",
            'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_BAD': "Mauvais éat"
        });
        translateProvider.translations('en', {
            'ACTIVITY_OTHER': "Other - I don't know",
                'ACTIVITY_ELECTRICITY': "Electricity",
                'ACTIVITY_PLUMBING': "Plumbing",
                'ACTIVITY_HEATING_AIRCONDITIONING': "Heating airconditioning",
                'ACTIVITY_CARPENTRY_WINDOW_VERANDA': "Carpentry window veranda",
                'ACTIVITY_LOCKSMITH': "Locksmith",
                'ACTIVITY_PAINTING_WALLS_FLOORS': "Painting walls floors",
                'ACTIVITY_WALLS_CEILING_ROOFS': "Walls ceiling roofs",
                'ACTIVITY_ISOLATION': "Isolation",
                'ACTIVITY_COUNCIL_ARCHI_LANDSCAPE': "Council archi landscape",
                'ACTIVITY_KITCHEN_BATHROOM': "Kitchen bathroom",
                'ACTIVITY_ROOFING_CARPENTRY': "Roofing carpentry",
                'ACTIVITY_PORTAL_GARAGE': "Garage portal",
                'ACTIVITY_GARDEN_TERRACE_FENCE': "Garden terrace fence",
                'ACTIVITY_CONSTRUCTION': "Construction",
                'ACTIVITY_EL_PLUG_CABLE': "Plug cable",
                'ACTIVITY_EL_LIGHTING': "Lighting",
                'ACTIVITY_EL_LIGHTING_INSIDE': "Inside",
                'ACTIVITY_EL_LIGHTING_EXTERIOR': "Exterior",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER': "Radiatior toweldryer",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR': "Radiatior",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER': "Towel dryer",
                'ACTIVITY_EL_BOILER_WATER_HEATER': "Boiler water heater",
                'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER': "Boiler",
                'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER': "Waterheater",
                'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK': "Hotwatertank",
                'ACTIVITY_EL_SWITCHBOARD': "Switchboard",
                'ACTIVITY_EL_ELECTRICMETER': "Electricmeter",
                'ACTIVITY_EL_AUTOMATION': "Automation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM': "Security alarm intercom",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS': "Alarms",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY': "Video security",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM': "Intercom",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD': "Keypad",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR': "Smokedetector",
                'ACTIVITY_PL_TOILETS': "Toilets",
                'ACTIVITY_PL_TOILETS_CLASSIC': "Classic",
                'ACTIVITY_PL_TOILETS_SUSPENDED': "Suspended",
                'ACTIVITY_PL_TOILETS_MECHANISM': "Mechanism",
                'ACTIVITY_PL_SHOWER': "Shower",
                'ACTIVITY_PL_SHOWER_SHOWER': "Shower",
                'ACTIVITY_PL_SHOWER_CABIN': "Cabin",
                'ACTIVITY_PL_SHOWER_COLUMN': "Column",
                'ACTIVITY_PL_SHOWER_DOOR': "Door",
                'ACTIVITY_PL_SHOWER_GLASS': "Glass",
                'ACTIVITY_PL_BATHTUBE': "Bathtube",
                'ACTIVITY_PL_BATHTUBE_BATH': "Bath",
                'ACTIVITY_PL_BATHTUBE_TAP_FAUCET': "Tap faucet",
                'ACTIVITY_PL_BATHTUBE_GLASS': "Glass",
                'ACTIVITY_PL_BASIN_SINK': "Basin sink",
                'ACTIVITY_PL_PIPING_CANALIZATION': "Piping canalization",
                'ACTIVITY_PL_BOILER_WATER_HEATER': "Boiler water heater",
                'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER': "Boiler",
                'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER': "Water heater",
                'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK': "Hot water tank",
                'ACTIVITY_PL_SOFTENER': "Softener",
                'ACTIVITY_HE_BOILER_WATER_HEATER': "Boiler water heater",
                'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER': "Boiler",
                'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER': "Water heater",
                'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK': "Hot water tank",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER': "Radiatior toweldryer",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR': "Radiatior",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER': "Towel dryer",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER': "Electric heater",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER': "Gas heater",
                'ACTIVITY_HE_FLOOR_HEATING': "Floor heating",
                'ACTIVITY_HE_THERMOSTAT': "Thermostat",
                'ACTIVITY_HE_AIR_CONDITIONER': "Air conditioner",
                'ACTIVITY_HE_HEAT_PUMP': "Heat pump",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE': "Stove insert fireplace",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE': "Wood burning stove",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE': "Pellet stove",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE': "Fireplace",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT': "Insert",
                'ACTIVITY_HE_VMC_VMC': "Vmc",
                'ACTIVITY_HE_VMC_SINGLE_FLOW': "Single flow",
                'ACTIVITY_HE_VMC_DOUBLE_FLOW': "Double flow",
                'ACTIVITY_CA_SINGLE_DOOR': "Single door",
                'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM': "Aluminium",
                'ACTIVITY_CA_SINGLE_DOOR_WOOD': "Wood",
                'ACTIVITY_CA_SINGLE_DOOR_PVC': "Pvc",
                'ACTIVITY_CA_REINFORCED_DOOR': "Reinforced door",
                'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM': "Aluminium",
                'ACTIVITY_CA_REINFORCED_DOOR_WOOD': "Wood",
                'ACTIVITY_CA_REINFORCED_DOOR_PVC': "Pvc",
                'ACTIVITY_CA_WINDOW_DOORWINDOW': "Window doorwindow",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT': "Roof window skylight",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW': "Window",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW': "Door window",
                'ACTIVITY_CA_SHUTTERS': "Shutters",
                'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS': "Electric rolling shutters",
                'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS': "Manual rolling shutters",
                'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS': "Swing shutters",
                'ACTIVITY_CA_STAIRCASE': "Staircase",
                'ACTIVITY_CA_MEZZANINE': "Mezzanine",
                'ACTIVITY_CA_CLOSETS_CUPBOARDS': "Closets cupboards",
                'ACTIVITY_CA_VERANDA': "Veranda",
                'ACTIVITY_LO_SINGLE_DOOR': "Single door",
                'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM': "Aluminium",
                'ACTIVITY_LO_SINGLE_DOOR_WOOD': "Wood",
                'ACTIVITY_LO_SINGLE_DOOR_PVC': "Pvc",
                'ACTIVITY_LO_REINFORCED_DOOR': "Reinforced door",
                'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM': "Aluminium",
                'ACTIVITY_LO_REINFORCED_DOOR_WOOD': "Wood",
                'ACTIVITY_LO_REINFORCED_DOOR_PVC': "Pvc",
                'ACTIVITY_LO_CLASSIC_LOCK': "Classic lock",
                'ACTIVITY_LO_MULTIPOINT_LOCK': "Multipoint lock",
                'ACTIVITY_LO_ELECTRIC_GACHE': "Electric gache",
                'ACTIVITY_LO_SHUTTERS': "Shutters",
                'ACTIVITY_LO_METALLIC_CURTAINS': "Metallic curtains",
                'ACTIVITY_PA_PAINT_AND_COATINGS': "Paint and coatings",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT': "Interior paint",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS': "Interior decorative coatings",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING': "Exterior painting",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS': "Exterior coatings",
                'ACTIVITY_PA_WALL_PAPER': "Wall paper",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE': "Interior floor",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET': "Floor tile",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET': "Parquet",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR': "Carpet",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE': "Plastic floor",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE': "Pierre",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE': "Concrete",
                'ACTIVITY_PA_OUTDOOR FLOOR': "Outdoor floor",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE': "Floor tile",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE': "Pierre",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE': "Concrete",
                'ACTIVITY_WA_BULKHEAD': "Bulkhead",
                'ACTIVITY_WA_CEILINGS': "Ceilings",
                'ACTIVITY_WA_ATTIC': "Attic",
                'ACTIVITY_WA_ATTIC_INSULATION': "Insulation",
                'ACTIVITY_WA_ATTIC_ADJUSTING': "Adjusting",
                'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING': "Insulation adjusting",
                'ACTIVITY_IS_INTERIOR_THERMIC': "Interior thermic",
                'ACTIVITY_IS_EXTERIOR_THERMIC': "Exterior thermic",
                'ACTIVITY_IS_ATTIC': "Attic",
                'ACTIVITY_IS_SOUNDPROOFING': "Soundproofing",
                'ACTIVITY_CO_ARCHITECT': "Architect",
                'ACTIVITY_CO_INTERIOR_DESIGNER': "Interior designer",
                'ACTIVITY_CO_DECORATION_INTERIOR_AMENAGMENT': "Decoration interior amenagment",
                'ACTIVITY_CO_LANDSCAPER': "Landscaper",
                'ACTIVITY_KI_FULL_KITCHEN': "Full kitchen",
                'ACTIVITY_KI_KITCHEN_FURNITURE': "Kitchen furniture",
                'ACTIVITY_KI_WORKPLAN_KITCHEN': "Workplan kitchen",
                'ACTIVITY_KI_BATHROOM': "Bathroom",
                'ACTIVITY_KI_BATHROOM_FURNITURE': "Bathroom furniture",
                'ACTIVITY_RO_ROOFING': "Roofing",
                'ACTIVITY_RO_ROOFING_TILES': "Tiles",
                'ACTIVITY_RO_ROOFING_SLATE': "Slate",
                'ACTIVITY_RO_ROOFING_ZINC': "Zinc",
                'ACTIVITY_RO_ROOFING_SHINGLE': "Shingle",
                'ACTIVITY_RO_ROOFING_SHEET_METAL': "Sheet metal",
                'ACTIVITY_RO_ROOFING_CHAUME': "Chaume",
                'ACTIVITY_RO_ROOFING_TERRASSE': "Terrasse",
                'ACTIVITY_RO_WOODEN_ROOFS': "Wooden roofs",
                'ACTIVITY_RO_METAL_FRAME': "Metal frame",
                'ACTIVITY_PO_WOODEN_PORTAL': "Wooden portal",
                'ACTIVITY_PO_ALUMINUM_METAL_PORTAL': "Aluminum metal portal",
                'ACTIVITY_PO_PVC PORTAL': "Pvc portal",
                'ACTIVITY_PO_WOODEN_GARAGE_DOOR': "Wooden garage door",
                'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR': "Aluminum metal garage door",
                'ACTIVITY_PO_PVC_GARAGE_DOOR': "Pvc garage door",
                'ACTIVITY_GA_GARDEN_GREEN_SPACES': "Garden green spaces",
                'ACTIVITY_GA_WOODEN_DECK': "Wooden deck",
                'ACTIVITY_GA_FENCED': "Fenced",
                'ACTIVITY_GA_FENCED_GRILLING': "Grilling",
                'ACTIVITY_GA_FENCED_CANNISSE': "Cannisse",
                'ACTIVITY_GA_FENCED_WOOD_PANELS': "Wood panels",
                'ACTIVITY_GA_FENCED_PVC_PANELS': "Pvc panels",
                'ACTIVITY_GA_WALL_DYKE': "Wall dyke",
                'ACTIVITY_GA_EARTHWORK': "Earthwork",
                'ACTIVITY_CO_HOUSE': "House",
                'ACTIVITY_CO_HOUSE_CLASSIC': "Classic",
                'ACTIVITY_CO_HOUSE_BRICK': "Brick",
                'ACTIVITY_CO_HOUSE_WOOD_FRAME': "Wood frame",
                'ACTIVITY_CO_HOUSE_BBC': "Bbc",
                'ACTIVITY_CO_GARAGE': "Garage",
                'ACTIVITY_CO_GARAGE_CONCRETE': "Concrete",
                'ACTIVITY_CO_GARAGE_METAL': "Metal",
                'ACTIVITY_CO_GARAGE_BRICK': "Brick",
                'ACTIVITY_CO_GARAGE_WOOD_FRAME': "Wood frame",
                'ACTIVITY_CO_HOUSE_EXTENSION': "House extension",
                'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK': "Blockwork",
                'ACTIVITY_CO_HOUSE_EXTENSION_BRICK': "Brick",
                'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME': "Wood frame",
                'ACTIVITY_CO_FOUNDATIONS': "Foundations",
                'ACTIVITY_CO_SWIMMING POOL': "Swimming pool",
                'ACTIVITY_EL_PLUG_CABLE_INSTALLATION': "Installation",
                'ACTIVITY_EL_LIGHTING_INSIDE_INSTALLATION': "Installation",
                'ACTIVITY_EL_LIGHTING_EXTERIOR_INSTALLATION': "Installation",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_INSTALLATION': "Installation",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_INSTALLATION': "Installation",
                'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
                'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_INSTALLATION': "Installation",
                'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_INSTALLATION': "Installation",
                'ACTIVITY_EL_SWITCHBOARD_INSTALLATION': "Installation",
                'ACTIVITY_EL_ELECTRICMETER_INSTALLATION': "Installation",
                'ACTIVITY_EL_AUTOMATION_INSTALLATION': "Installation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_INSTALLATION': "Installation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_INSTALLATION': "Installation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_INSTALLATION': "Installation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_INSTALLATION': "Installation",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_INSTALLATION': "Installation",
                'ACTIVITY_PL_TOILETS_CLASSIC_INSTALLATION': "Installation",
                'ACTIVITY_PL_TOILETS_SUSPENDED_INSTALLATION': "Installation",
                'ACTIVITY_PL_TOILETS_MECHANISM_INSTALLATION': "Installation",
                'ACTIVITY_PL_SHOWER_SHOWER_INSTALLATION': "Installation",
                'ACTIVITY_PL_SHOWER_CABIN_INSTALLATION': "Installation",
                'ACTIVITY_PL_SHOWER_COLUMN_INSTALLATION': "Installation",
                'ACTIVITY_PL_SHOWER_DOOR_INSTALLATION': "Installation",
                'ACTIVITY_PL_SHOWER_GLASS_INSTALLATION': "Installation",
                'ACTIVITY_PL_BATHTUBE_BATH_INSTALLATION': "Installation",
                'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_INSTALLATION': "Installation",
                'ACTIVITY_PL_BATHTUBE_GLASS_INSTALLATION': "Installation",
                'ACTIVITY_PL_BASIN_SINK_INSTALLATION': "Installation",
                'ACTIVITY_PL_PIPING_CANALIZATION_INSTALLATION': "Installation",
                'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
                'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_INSTALLATION': "Installation",
                'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_INSTALLATION': "Installation",
                'ACTIVITY_PL_SOFTENER_INSTALLATION': "Installation",
                'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_INSTALLATION': "Installation",
                'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_INSTALLATION': "Installation",
                'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_INSTALLATION': "Installation",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_INSTALLATION': "Installation",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_INSTALLATION': "Installation",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_INSTALLATION': "Installation",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_INSTALLATION': "Installation",
                'ACTIVITY_HE_FLOOR_HEATING_INSTALLATION': "Installation",
                'ACTIVITY_HE_THERMOSTAT_INSTALLATION': "Installation",
                'ACTIVITY_HE_AIR_CONDITIONER_INSTALLATION': "Installation",
                'ACTIVITY_HE_HEAT_PUMP_INSTALLATION': "Installation",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_INSTALLATION': "Installation",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_INSTALLATION': "Installation",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_INSTALLATION': "Installation",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_INSTALLATION': "Installation",
                'ACTIVITY_HE_VMC_SINGLE_FLOW_INSTALLATION': "Installation",
                'ACTIVITY_HE_VMC_DOUBLE_FLOW_INSTALLATION': "Installation",
                'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_INSTALLATION': "Installation",
                'ACTIVITY_CA_SINGLE_DOOR_WOOD_INSTALLATION': "Installation",
                'ACTIVITY_CA_SINGLE_DOOR_PVC_INSTALLATION': "Installation",
                'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_INSTALLATION': "Installation",
                'ACTIVITY_CA_REINFORCED_DOOR_WOOD_INSTALLATION': "Installation",
                'ACTIVITY_CA_REINFORCED_DOOR_PVC_INSTALLATION': "Installation",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_INSTALLATION': "Installation",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_INSTALLATION': "Installation",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_INSTALLATION': "Installation",
                'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_INSTALLATION': "Installation",
                'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_INSTALLATION': "Installation",
                'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_INSTALLATION': "Installation",
                'ACTIVITY_CA_STAIRCASE_INSTALLATION': "Installation",
                'ACTIVITY_CA_MEZZANINE_INSTALLATION': "Installation",
                'ACTIVITY_CA_CLOSETS_CUPBOARDS_INSTALLATION': "Installation",
                'ACTIVITY_CA_VERANDA_INSTALLATION': "Installation",
                'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_INSTALLATION': "Installation",
                'ACTIVITY_LO_SINGLE_DOOR_WOOD_INSTALLATION': "Installation",
                'ACTIVITY_LO_SINGLE_DOOR_PVC_INSTALLATION': "Installation",
                'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_INSTALLATION': "Installation",
                'ACTIVITY_LO_REINFORCED_DOOR_WOOD_INSTALLATION': "Installation",
                'ACTIVITY_LO_REINFORCED_DOOR_PVC_INSTALLATION': "Installation",
                'ACTIVITY_LO_CLASSIC_LOCK_INSTALLATION': "Installation",
                'ACTIVITY_LO_MULTIPOINT_LOCK_INSTALLATION': "Installation",
                'ACTIVITY_LO_ELECTRIC_GACHE_INSTALLATION': "Installation",
                'ACTIVITY_LO_SHUTTERS_INSTALLATION': "Installation",
                'ACTIVITY_LO_METALLIC_CURTAINS_INSTALLATION': "Installation",
                'ACTIVITY_WA_BULKHEAD_INSTALLATION': "Installation",
                'ACTIVITY_WA_CEILINGS_INSTALLATION': "Installation",
                'ACTIVITY_WA_ATTIC_INSULATION_INSTALLATION': "Installation",
                'ACTIVITY_WA_ATTIC_ADJUSTING_INSTALLATION': "Installation",
                'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING_INSTALLATION': "Installation",
                'ACTIVITY_IS_INTERIOR_THERMIC_INSTALLATION': "Installation",
                'ACTIVITY_IS_EXTERIOR_THERMIC_INSTALLATION': "Installation",
                'ACTIVITY_IS_ATTIC_INSTALLATION': "Installation",
                'ACTIVITY_IS_SOUNDPROOFING_INSTALLATION': "Installation",
                'ACTIVITY_KI_FULL_KITCHEN_INSTALLATION': "Installation",
                'ACTIVITY_KI_KITCHEN_FURNITURE_INSTALLATION': "Installation",
                'ACTIVITY_KI_WORKPLAN_KITCHEN_INSTALLATION': "Installation",
                'ACTIVITY_KI_BATHROOM_INSTALLATION': "Installation",
                'ACTIVITY_KI_BATHROOM_FURNITURE_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_TILES_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_SLATE_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_ZINC_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_SHINGLE_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_SHEET_METAL_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_CHAUME_INSTALLATION': "Installation",
                'ACTIVITY_RO_ROOFING_TERRASSE_INSTALLATION': "Installation",
                'ACTIVITY_RO_WOODEN_ROOFS_INSTALLATION': "Installation",
                'ACTIVITY_RO_METAL_FRAME_INSTALLATION': "Installation",
                'ACTIVITY_PO_WOODEN_PORTAL_INSTALLATION': "Installation",
                'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_INSTALLATION': "Installation",
                'ACTIVITY_PO_PVC PORTAL_INSTALLATION': "Installation",
                'ACTIVITY_PO_WOODEN_GARAGE_DOOR_INSTALLATION': "Installation",
                'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_INSTALLATION': "Installation",
                'ACTIVITY_PO_PVC_GARAGE_DOOR_INSTALLATION': "Installation",
                'ACTIVITY_GA_GARDEN_GREEN_SPACES_INSTALLATION': "Installation",
                'ACTIVITY_GA_WOODEN_DECK_INSTALLATION': "Installation",
                'ACTIVITY_GA_FENCED_GRILLING_INSTALLATION': "Installation",
                'ACTIVITY_GA_FENCED_CANNISSE_INSTALLATION': "Installation",
                'ACTIVITY_GA_FENCED_WOOD_PANELS_INSTALLATION': "Installation",
                'ACTIVITY_GA_FENCED_PVC_PANELS_INSTALLATION': "Installation",
                'ACTIVITY_GA_WALL_DYKE_INSTALLATION': "Installation",
                'ACTIVITY_EL_PLUG_CABLE_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_LIGHTING_INSIDE_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_LIGHTING_EXTERIOR_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SWITCHBOARD_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_ELECTRICMETER_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_TOILETS_CLASSIC_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_TOILETS_SUSPENDED_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_TOILETS_MECHANISM_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SHOWER_SHOWER_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SHOWER_CABIN_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SHOWER_COLUMN_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SHOWER_DOOR_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SHOWER_GLASS_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BATHTUBE_BATH_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BATHTUBE_GLASS_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BASIN_SINK_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_PIPING_CANALIZATION_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_REPLACEMENT': "Replacement",
                'ACTIVITY_PL_SOFTENER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_FLOOR_HEATING_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_THERMOSTAT_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_AIR_CONDITIONER_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_HEAT_PUMP_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_VMC_SINGLE_FLOW_REPLACEMENT': "Replacement",
                'ACTIVITY_HE_VMC_DOUBLE_FLOW_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SINGLE_DOOR_WOOD_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SINGLE_DOOR_PVC_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_REINFORCED_DOOR_WOOD_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_REINFORCED_DOOR_PVC_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_STAIRCASE_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_MEZZANINE_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_CLOSETS_CUPBOARDS_REPLACEMENT': "Replacement",
                'ACTIVITY_CA_VERANDA_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_SINGLE_DOOR_WOOD_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_SINGLE_DOOR_PVC_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_REINFORCED_DOOR_WOOD_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_REINFORCED_DOOR_PVC_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_CLASSIC_LOCK_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_MULTIPOINT_LOCK_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_ELECTRIC_GACHE_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_SHUTTERS_REPLACEMENT': "Replacement",
                'ACTIVITY_LO_METALLIC_CURTAINS_REPLACEMENT': "Replacement",
                'ACTIVITY_WA_BULKHEAD_REPLACEMENT': "Replacement",
                'ACTIVITY_WA_CEILINGS_REPLACEMENT': "Replacement",
                'ACTIVITY_WA_ATTIC_INSULATION_REPLACEMENT': "Replacement",
                'ACTIVITY_WA_ATTIC_ADJUSTING_REPLACEMENT': "Replacement",
                'ACTIVITY_WA_ATTIC_INSULATION_ADJUSTING_REPLACEMENT': "Replacement",
                'ACTIVITY_IS_INTERIOR_THERMIC_REPLACEMENT': "Replacement",
                'ACTIVITY_IS_EXTERIOR_THERMIC_REPLACEMENT': "Replacement",
                'ACTIVITY_IS_ATTIC_REPLACEMENT': "Replacement",
                'ACTIVITY_IS_SOUNDPROOFING_REPLACEMENT': "Replacement",
                'ACTIVITY_KI_FULL_KITCHEN_REPLACEMENT': "Replacement",
                'ACTIVITY_KI_KITCHEN_FURNITURE_REPLACEMENT': "Replacement",
                'ACTIVITY_KI_WORKPLAN_KITCHEN_REPLACEMENT': "Replacement",
                'ACTIVITY_KI_BATHROOM_REPLACEMENT': "Replacement",
                'ACTIVITY_KI_BATHROOM_FURNITURE_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_TILES_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_SLATE_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_ZINC_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_SHINGLE_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_SHEET_METAL_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_CHAUME_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_ROOFING_TERRASSE_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_WOODEN_ROOFS_REPLACEMENT': "Replacement",
                'ACTIVITY_RO_METAL_FRAME_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_WOODEN_PORTAL_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_PVC PORTAL_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_WOODEN_GARAGE_DOOR_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_REPLACEMENT': "Replacement",
                'ACTIVITY_PO_PVC_GARAGE_DOOR_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_GARDEN_GREEN_SPACES_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_WOODEN_DECK_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_FENCED_GRILLING_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_FENCED_CANNISSE_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_FENCED_WOOD_PANELS_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_FENCED_PVC_PANELS_REPLACEMENT': "Replacement",
                'ACTIVITY_GA_WALL_DYKE_REPLACEMENT': "Replacement",
                'ACTIVITY_EL_PLUG_CABLE_REPAIR': "Repair",
                'ACTIVITY_EL_LIGHTING_INSIDE_REPAIR': "Repair",
                'ACTIVITY_EL_LIGHTING_EXTERIOR_REPAIR': "Repair",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_RADIATIOR_REPAIR': "Repair",
                'ACTIVITY_EL_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPAIR': "Repair",
                'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_REPAIR': "Repair",
                'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_REPAIR': "Repair",
                'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_REPAIR': "Repair",
                'ACTIVITY_EL_SWITCHBOARD_REPAIR': "Repair",
                'ACTIVITY_EL_ELECTRICMETER_REPAIR': "Repair",
                'ACTIVITY_EL_AUTOMATION_REPAIR': "Repair",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_REPAIR': "Repair",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_REPAIR': "Repair",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_INTERCOM_REPAIR': "Repair",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_KEYPAD_REPAIR': "Repair",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_REPAIR': "Repair",
                'ACTIVITY_PL_TOILETS_CLASSIC_REPAIR': "Repair",
                'ACTIVITY_PL_TOILETS_SUSPENDED_REPAIR': "Repair",
                'ACTIVITY_PL_TOILETS_MECHANISM_REPAIR': "Repair",
                'ACTIVITY_PL_SHOWER_SHOWER_REPAIR': "Repair",
                'ACTIVITY_PL_SHOWER_CABIN_REPAIR': "Repair",
                'ACTIVITY_PL_SHOWER_COLUMN_REPAIR': "Repair",
                'ACTIVITY_PL_SHOWER_DOOR_REPAIR': "Repair",
                'ACTIVITY_PL_SHOWER_GLASS_REPAIR': "Repair",
                'ACTIVITY_PL_BATHTUBE_BATH_REPAIR': "Repair",
                'ACTIVITY_PL_BATHTUBE_TAP_FAUCET_REPAIR': "Repair",
                'ACTIVITY_PL_BATHTUBE_GLASS_REPAIR': "Repair",
                'ACTIVITY_PL_BASIN_SINK_REPAIR': "Repair",
                'ACTIVITY_PL_PIPING_CANALIZATION_REPAIR': "Repair",
                'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_REPAIR': "Repair",
                'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_REPAIR': "Repair",
                'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_REPAIR': "Repair",
                'ACTIVITY_PL_SOFTENER_REPAIR': "Repair",
                'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_REPAIR': "Repair",
                'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_REPAIR': "Repair",
                'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_REPAIR': "Repair",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_RADIATIOR_REPAIR': "Repair",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_TOWEL_DRYER_REPAIR': "Repair",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_ELECTRIC_HEATER_REPAIR': "Repair",
                'ACTIVITY_HE_RADIATIOR_TOWELDRYER_GAS_HEATER_REPAIR': "Repair",
                'ACTIVITY_HE_FLOOR_HEATING_REPAIR': "Repair",
                'ACTIVITY_HE_THERMOSTAT_REPAIR': "Repair",
                'ACTIVITY_HE_AIR_CONDITIONER_REPAIR': "Repair",
                'ACTIVITY_HE_HEAT_PUMP_REPAIR': "Repair",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_REPAIR': "Repair",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_REPAIR': "Repair",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_REPAIR': "Repair",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_REPAIR': "Repair",
                'ACTIVITY_HE_VMC_SINGLE_FLOW_REPAIR': "Repair",
                'ACTIVITY_HE_VMC_DOUBLE_FLOW_REPAIR': "Repair",
                'ACTIVITY_CA_SINGLE_DOOR_ALUMINIUM_REPAIR': "Repair",
                'ACTIVITY_CA_SINGLE_DOOR_WOOD_REPAIR': "Repair",
                'ACTIVITY_CA_SINGLE_DOOR_PVC_REPAIR': "Repair",
                'ACTIVITY_CA_REINFORCED_DOOR_ALUMINIUM_REPAIR': "Repair",
                'ACTIVITY_CA_REINFORCED_DOOR_WOOD_REPAIR': "Repair",
                'ACTIVITY_CA_REINFORCED_DOOR_PVC_REPAIR': "Repair",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_ROOF_WINDOW_SKYLIGHT_REPAIR': "Repair",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_WINDOW_REPAIR': "Repair",
                'ACTIVITY_CA_WINDOW_DOORWINDOW_DOOR_WINDOW_REPAIR': "Repair",
                'ACTIVITY_CA_SHUTTERS_ELECTRIC_ROLLING_SHUTTERS_REPAIR': "Repair",
                'ACTIVITY_CA_SHUTTERS_MANUAL_ROLLING_SHUTTERS_REPAIR': "Repair",
                'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_REPAIR': "Repair",
                'ACTIVITY_CA_STAIRCASE_REPAIR': "Repair",
                'ACTIVITY_CA_MEZZANINE_REPAIR': "Repair",
                'ACTIVITY_CA_CLOSETS_CUPBOARDS_REPAIR': "Repair",
                'ACTIVITY_CA_VERANDA_REPAIR': "Repair",
                'ACTIVITY_LO_SINGLE_DOOR_ALUMINIUM_REPAIR': "Repair",
                'ACTIVITY_LO_SINGLE_DOOR_WOOD_REPAIR': "Repair",
                'ACTIVITY_LO_SINGLE_DOOR_PVC_REPAIR': "Repair",
                'ACTIVITY_LO_REINFORCED_DOOR_ALUMINIUM_REPAIR': "Repair",
                'ACTIVITY_LO_REINFORCED_DOOR_WOOD_REPAIR': "Repair",
                'ACTIVITY_LO_REINFORCED_DOOR_PVC_REPAIR': "Repair",
                'ACTIVITY_LO_CLASSIC_LOCK_REPAIR': "Repair",
                'ACTIVITY_LO_MULTIPOINT_LOCK_REPAIR': "Repair",
                'ACTIVITY_LO_ELECTRIC_GACHE_REPAIR': "Repair",
                'ACTIVITY_LO_SHUTTERS_REPAIR': "Repair",
                'ACTIVITY_LO_METALLIC_CURTAINS_REPAIR': "Repair",
                'ACTIVITY_WA_BULKHEAD_REPAIR': "Repair",
                'ACTIVITY_WA_CEILINGS_REPAIR': "Repair",
                'ACTIVITY_WA_ATTIC_INSULATION_REPAIR': "Repair",
                'ACTIVITY_IS_INTERIOR_THERMIC_REPAIR': "Repair",
                'ACTIVITY_IS_EXTERIOR_THERMIC_REPAIR': "Repair",
                'ACTIVITY_IS_ATTIC_REPAIR': "Repair",
                'ACTIVITY_IS_SOUNDPROOFING_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_TILES_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_SLATE_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_ZINC_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_SHINGLE_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_SHEET_METAL_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_CHAUME_REPAIR': "Repair",
                'ACTIVITY_RO_ROOFING_TERRASSE_REPAIR': "Repair",
                'ACTIVITY_RO_WOODEN_ROOFS_REPAIR': "Repair",
                'ACTIVITY_RO_METAL_FRAME_REPAIR': "Repair",
                'ACTIVITY_PO_WOODEN_PORTAL_REPAIR': "Repair",
                'ACTIVITY_PO_ALUMINUM_METAL_PORTAL_REPAIR': "Repair",
                'ACTIVITY_PO_PVC PORTAL_REPAIR': "Repair",
                'ACTIVITY_PO_WOODEN_GARAGE_DOOR_REPAIR': "Repair",
                'ACTIVITY_PO_ALUMINUM_METAL_GARAGE_DOOR_REPAIR': "Repair",
                'ACTIVITY_PO_PVC_GARAGE_DOOR_REPAIR': "Repair",
                'ACTIVITY_GA_GARDEN_GREEN_SPACES_REPAIR': "Repair",
                'ACTIVITY_GA_WOODEN_DECK_REPAIR': "Repair",
                'ACTIVITY_GA_FENCED_GRILLING_REPAIR': "Repair",
                'ACTIVITY_GA_FENCED_CANNISSE_REPAIR': "Repair",
                'ACTIVITY_GA_FENCED_WOOD_PANELS_REPAIR': "Repair",
                'ACTIVITY_GA_FENCED_PVC_PANELS_REPAIR': "Repair",
                'ACTIVITY_GA_WALL_DYKE_REPAIR': "Repair",
                'ACTIVITY_EL_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Maintenance",
                'ACTIVITY_EL_BOILER_WATER_HEATER_WATERHEATER_MAINTENANCE': "Maintenance",
                'ACTIVITY_EL_BOILER_WATER_HEATER_HOTWATERTANK_MAINTENANCE': "Maintenance",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_ALARMS_MAINTENANCE': "Maintenance",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_VIDEO_SECURITY_MAINTENANCE': "Maintenance",
                'ACTIVITY_EL_SECURITY_ALARM_INTERCOM_SMOKEDETECTOR_MAINTENANCE': "Maintenance",
                'ACTIVITY_PL_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Maintenance",
                'ACTIVITY_PL_BOILER_WATER_HEATER_WATER_HEATER_MAINTENANCE': "Maintenance",
                'ACTIVITY_PL_BOILER_WATER_HEATER_HOT_WATER_TANK_MAINTENANCE': "Maintenance",
                'ACTIVITY_PL_SOFTENER_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_BOILER_WATER_HEATER_BOILER_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_BOILER_WATER_HEATER_WATER_HEATER_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_BOILER_WATER_HEATER_HOT_WATER_TANK_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_AIR_CONDITIONER_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_WOOD_BURNING_STOVE_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_PELLET_STOVE_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_FIREPLACE_MAINTENANCE': "Maintenance",
                'ACTIVITY_HE_STOVE_INSERT_FIREPLACE_INSERT_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_TILES_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_SLATE_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_ZINC_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_SHINGLE_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_SHEET_METAL_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_CHAUME_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_ROOFING_TERRASSE_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_WOODEN_ROOFS_MAINTENANCE': "Maintenance",
                'ACTIVITY_RO_METAL_FRAME_MAINTENANCE': "Maintenance",
                'ACTIVITY_KI_FULL_KITCHEN_CREATION': "Creation",
                'ACTIVITY_KI_BATHROOM_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_CLASSIC_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_BRICK_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_WOOD_FRAME_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_BBC_CREATION': "Creation",
                'ACTIVITY_CO_GARAGE_CONCRETE_CREATION': "Creation",
                'ACTIVITY_CO_GARAGE_METAL_CREATION': "Creation",
                'ACTIVITY_CO_GARAGE_BRICK_CREATION': "Creation",
                'ACTIVITY_CO_GARAGE_WOOD_FRAME_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_EXTENSION_BRICK_CREATION': "Creation",
                'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME_CREATION': "Creation",
                'ACTIVITY_CO_FOUNDATIONS_CREATION': "Creation",
                'ACTIVITY_CO_SWIMMING POOL_CREATION': "Creation",
                'ACTIVITY_CA_SINGLE_DOOR_WOOD_RENOVATION': "Renovation",
                'ACTIVITY_CA_REINFORCED_DOOR_WOOD_RENOVATION': "Renovation",
                'ACTIVITY_CA_SHUTTERS_SWING_SHUTTERS_RENOVATION': "Renovation",
                'ACTIVITY_GA_GARDEN_GREEN_SPACES_RENOVATION': "Renovation",
                'ACTIVITY_GA_WOODEN_DECK_RENOVATION': "Renovation",
                'ACTIVITY_GA_FENCED_WOOD_PANELS_RENOVATION': "Renovation",
                'ACTIVITY_GA_WALL_DYKE_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_CLASSIC_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_BRICK_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_WOOD_FRAME_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_BBC_RENOVATION': "Renovation",
                'ACTIVITY_CO_GARAGE_CONCRETE_RENOVATION': "Renovation",
                'ACTIVITY_CO_GARAGE_METAL_RENOVATION': "Renovation",
                'ACTIVITY_CO_GARAGE_BRICK_RENOVATION': "Renovation",
                'ACTIVITY_CO_GARAGE_WOOD_FRAME_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_EXTENSION_BLOCKWORK_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_EXTENSION_BRICK_RENOVATION': "Renovation",
                'ACTIVITY_CO_HOUSE_EXTENSION_WOOD_FRAME_RENOVATION': "Renovation",
                'ACTIVITY_CO_FOUNDATIONS_RENOVATION': "Renovation",
                'ACTIVITY_CO_SWIMMING POOL_RENOVATION': "Renovation",
                'ACTIVITY_PL_TOILETS_CLASSIC_UNCORK': "Uncork",
                'ACTIVITY_PL_TOILETS_SUSPENDED_UNCORK': "Uncork",
                'ACTIVITY_PL_SHOWER_SHOWER_UNCORK': "Uncork",
                'ACTIVITY_PL_BATHTUBE_BATH_UNCORK': "Uncork",
                'ACTIVITY_PL_BASIN_SINK_UNCORK': "Uncork",
                'ACTIVITY_PL_PIPING_CANALIZATION_UNCORK': "Uncork",
                'ACTIVITY_LO_METALLIC_CURTAINS_L30M2': "Less than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_L30M2': "Less than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_L30M2': "Less than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_L30M2': "Less than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_L30M2': "Less than 30m²",
                'ACTIVITY_PA_WALL_PAPER_L30M2': "Less than 30m²",
                'ACTIVITY_LO_METALLIC_CURTAINS_O30M2': "More than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_O30M2': "More than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_O30M2': "More than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_O30M2': "More than 30m²",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_O30M2': "More than 30m²",
                'ACTIVITY_PA_WALL_PAPER_O30M2': "More than 30m²",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_L20M2': "Less than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_O20M2': "More than 20m²",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_O20M2': "More than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_O20M2': "More than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_O20M2': "More than 20m²",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_O20M2': "More than 20m²",
                'ACTIVITY_LO_METALLIC_CURTAINS_GOOD': "Good condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_GOOD': "Good condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_GOOD': "Good condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_GOOD': "Good condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_GOOD': "Good condition",
                'ACTIVITY_PA_WALL_PAPER_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_GOOD': "Good condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_GOOD': "Good condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_GOOD': "Good condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_GOOD': "Good condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_GOOD': "Good condition",
                'ACTIVITY_LO_METALLIC_CURTAINS_MIDDLE': "Average condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_MIDDLE': "Average condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_MIDDLE': "Average condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_MIDDLE': "Average condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_MIDDLE': "Average condition",
                'ACTIVITY_PA_WALL_PAPER_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_MIDDLE': "Average condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_MIDDLE': "Average condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_MIDDLE': "Average condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_MIDDLE': "Average condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_MIDDLE': "Average condition",
                'ACTIVITY_LO_METALLIC_CURTAINS_BAD': "Bad condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR PAINT_BAD': "Bad condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_INTERIOR_DECORATIVE_COATINGS_BAD': "Bad condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_PAINTING_BAD': "Bad condition",
                'ACTIVITY_PA_PAINT_AND_COATINGS_EXTERIOR_COATINGS_BAD': "Bad condition",
                'ACTIVITY_PA_WALL_PAPER_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_FLOOR TILE_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PARQUET_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CARPET_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PLASTIC FLOOR_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_PIERRE_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_BAD': "Bad condition",
                'ACTIVITY_PA_INTERIOR FLOOR_CONCRETE_BAD': "Bad condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_FLOOR TILE_BAD': "Bad condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_PIERRE_BAD': "Bad condition",
                'ACTIVITY_PA_OUTDOOR FLOOR_CONCRETE_BAD': "Bad condition"
        });
    }])
;
