angular.module('Yaka')
    .config(['cloudinaryProvider', function (cloudinaryProvider) {
        cloudinaryProvider
            .set("cloud_name", "yaka")
            .set("upload_preset", "cxsdlf5n");
    }])
    .config(['uiGmapGoogleMapApiProvider', function (GoogleMapApi) {
        GoogleMapApi.configure({
            key: 'AIzaSyDtq1oFK_ku6rSm9OHM8Q0MlHeOYzOWgr8',
            libraries: 'weather,geometry,visualization'
            // v: '3.20',
        });
    }])
    .config(['$translateProvider', function (translateProvider) {
        // Simply register translation table as object hash
        translateProvider.useSanitizeValueStrategy('escape');
        translateProvider.translations('en', {
            'ACTIVITY_OTHER': "Other - I don't know",
            'ACTIVITY_PLUMBER': "Plumber",
            'ACTIVITY_LOCKSMITH': "Locksmith",
            'ACTIVITY_CARPENTER': "Carpenter",
            'ACTIVITY_ELECTRICIAN': "Electrician",
            'ACTIVITY_PAINTER': "Painter",
            'ACTIVITY_TILESETTER': "Tilesetter",
            'ACTIVITY_PL_WC': "Wc",
            'ACTIVITY_PL_SHOWER': "Shower",
            'ACTIVITY_PL_BATH': "Bath",
            'ACTIVITY_PL_SINK': "Sink",
            'ACTIVITY_PL_WATER_VALVE': "Water Valve",
            'ACTIVITY_PL_HOT_WATER_TANK': "Hot Water Tank",
            'ACTIVITY_PL_RADIATOR': "Radiator",
            'ACTIVITY_PL_BOILER_WATER_HEATER': "Boiler Water Heater",
            'ACTIVITY_LO_SIMPLE_DOOR': "Simple Door",
            'ACTIVITY_LO_SECURITY_DOOR': "Security Door",
            'ACTIVITY_LO_SIMPLE_LOCK': "Simple Lock",
            'ACTIVITY_LO_SECURITY_LOCK': "Security Lock",
            'ACTIVITY_LO_ELECTRIC_LOCK': "Electric Lock",
            'ACTIVITY_LO_PORTAL': "Portal",
            'ACTIVITY_LO_ELECTRIC_PORTAL': "Electric Portal",
            'ACTIVITY_CA_SIMPLE_GLAZED': "Simple Glazed",
            'ACTIVITY_CA_SIMPLE_GLAZED_WOOD': "Simple Glazed Wood",
            'ACTIVITY_CA_SIMPLE_GLAZED_PVC': "Simple Glazed Pvc",
            'ACTIVITY_CA_SIMPLE_GLAZED_ALU': "Simple Glazed Alu",
            'ACTIVITY_CA_DOUBLE_GLAZED': "Double Glazed",
            'ACTIVITY_CA_DOUBLE_GLAZED_WOOD': "Double Glazed Wood",
            'ACTIVITY_CA_DOUBLE_GLAZED_PVC': "Double Glazed Pvc",
            'ACTIVITY_CA_DOUBLE_GLAZED_ALU': "Double Glazed Alu",
            'ACTIVITY_CA_SIMPLE_DOOR': "Simple Door",
            'ACTIVITY_CA_SIMPLE_DOOR_WOOD': "Simple Door Wood",
            'ACTIVITY_CA_SIMPLE_DOOR_PVC': "Simple Door Pvc",
            'ACTIVITY_CA_SIMPLE_DOOR_ALU': "Simple Door Alu",
            'ACTIVITY_CA_SECURITY_DOOR': "Security Door",
            'ACTIVITY_CA_SECURITY_DOOR_WOOD': "Security Door Wood",
            'ACTIVITY_CA_SECURITY_DOOR_PVC': "Security Door Pvc",
            'ACTIVITY_CA_SECURITY_DOOR_ALU': "Security Door Alu",
            'ACTIVITY_CA_SHUTTER': "Shutter",
            'ACTIVITY_CA_SHUTTER_MANUAL': "Shutter Manual",
            'ACTIVITY_CA_SHUTTER_ROLLING': "Shutter Rolling",
            'ACTIVITY_CA_SHUTTER_ROLLING_ELEC': "Shutter Rolling Elec",
            'ACTIVITY_CA_GARAGE_PORTAL': "Garage Portal",
            'ACTIVITY_CA_GARAGE_PORTAL_ELECTRIC': "Garage Portal Electric",
            'ACTIVITY_EL_PLUG': "Plug",
            'ACTIVITY_EL_SWITCH': "Switch",
            'ACTIVITY_EL_INTERCOM': "Intercom",
            'ACTIVITY_EL_SWITCHBOARD': "Switchboard",
            'ACTIVITY_EL_CIRCUIT_BREAKER': "Circuit Breaker",
            'ACTIVITY_PA_EXTERIOR': "Exterior",
            'ACTIVITY_PA_EXTERIOR_WALL': "Exterior Wall",
            'ACTIVITY_PA_EXTERIOR_FENCE': "Exterior Fence",
            'ACTIVITY_PA_INTERIOR': "Interior",
            'ACTIVITY_PA_INTERIOR_ROOM': "Interior Room",
            'ACTIVITY_PA_INTERIOR_WALL': "Interior Wall",
            'ACTIVITY_PA_INTERIOR_CEILING': "Interior Ceiling",
            'ACTIVITY_TI_FLOOR': "Floor",
            'ACTIVITY_TI_WALL': "Wall",
            'ACTIVITY_TI_FLOOR_AND_WALL': "Floor And Wall",
            'ACTIVITY_PL_WC_REPAIR': "Repair",
            'ACTIVITY_PL_SHOWER_REPAIR': "Repair",
            'ACTIVITY_PL_BATH_REPAIR': "Repair",
            'ACTIVITY_PL_SINK_REPAIR': "Repair",
            'ACTIVITY_PL_WATER_VALVE_REPAIR': "Repair",
            'ACTIVITY_PL_HOT_WATER_TANK_REPAIR': "Repair",
            'ACTIVITY_PL_RADIATOR_REPAIR': "Repair",
            'ACTIVITY_PL_BOILER_WATER_HEATER_REPAIR': "Repair",
            'ACTIVITY_LO_SIMPLE_DOOR_REPAIR': "Repair",
            'ACTIVITY_LO_SECURITY_DOOR_REPAIR': "Repair",
            'ACTIVITY_LO_SIMPLE_LOCK_REPAIR': "Repair",
            'ACTIVITY_LO_SECURITY_LOCK_REPAIR': "Repair",
            'ACTIVITY_LO_ELECTRIC_LOCK_REPAIR': "Repair",
            'ACTIVITY_LO_PORTAL_REPAIR': "Repair",
            'ACTIVITY_LO_ELECTRIC_PORTAL_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_GLAZED_WOOD_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_GLAZED_PVC_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_GLAZED_ALU_REPAIR': "Repair",
            'ACTIVITY_CA_DOUBLE_GLAZED_WOOD_REPAIR': "Repair",
            'ACTIVITY_CA_DOUBLE_GLAZED_PVC_REPAIR': "Repair",
            'ACTIVITY_CA_DOUBLE_GLAZED_ALU_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_DOOR_WOOD_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_DOOR_PVC_REPAIR': "Repair",
            'ACTIVITY_CA_SIMPLE_DOOR_ALU_REPAIR': "Repair",
            'ACTIVITY_CA_SECURITY_DOOR_WOOD_REPAIR': "Repair",
            'ACTIVITY_CA_SECURITY_DOOR_PVC_REPAIR': "Repair",
            'ACTIVITY_CA_SECURITY_DOOR_ALU_REPAIR': "Repair",
            'ACTIVITY_CA_SHUTTER_MANUAL_REPAIR': "Repair",
            'ACTIVITY_CA_SHUTTER_ROLLING_REPAIR': "Repair",
            'ACTIVITY_CA_SHUTTER_ROLLING_ELEC_REPAIR': "Repair",
            'ACTIVITY_CA_GARAGE_PORTAL_REPAIR': "Repair",
            'ACTIVITY_CA_GARAGE_PORTAL_ELECTRIC_REPAIR': "Repair",
            'ACTIVITY_EL_PLUG_REPAIR': "Repair",
            'ACTIVITY_EL_SWITCH_REPAIR': "Repair",
            'ACTIVITY_EL_INTERCOM_REPAIR': "Repair",
            'ACTIVITY_EL_SWITCHBOARD_REPAIR': "Repair",
            'ACTIVITY_EL_CIRCUIT_BREAKER_REPAIR': "Repair",
            'ACTIVITY_PL_WC_CHANGE': "Change",
            'ACTIVITY_PL_SHOWER_CHANGE': "Change",
            'ACTIVITY_PL_BATH_CHANGE': "Change",
            'ACTIVITY_PL_SINK_CHANGE': "Change",
            'ACTIVITY_PL_WATER_VALVE_CHANGE': "Change",
            'ACTIVITY_PL_HOT_WATER_TANK_CHANGE': "Change",
            'ACTIVITY_PL_RADIATOR_CHANGE': "Change",
            'ACTIVITY_PL_BOILER_WATER_HEATER_CHANGE': "Change",
            'ACTIVITY_LO_SIMPLE_DOOR_CHANGE': "Change",
            'ACTIVITY_LO_SECURITY_DOOR_CHANGE': "Change",
            'ACTIVITY_LO_SIMPLE_LOCK_CHANGE': "Change",
            'ACTIVITY_LO_SECURITY_LOCK_CHANGE': "Change",
            'ACTIVITY_LO_ELECTRIC_LOCK_CHANGE': "Change",
            'ACTIVITY_LO_PORTAL_CHANGE': "Change",
            'ACTIVITY_LO_ELECTRIC_PORTAL_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_GLAZED_WOOD_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_GLAZED_PVC_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_GLAZED_ALU_CHANGE': "Change",
            'ACTIVITY_CA_DOUBLE_GLAZED_WOOD_CHANGE': "Change",
            'ACTIVITY_CA_DOUBLE_GLAZED_PVC_CHANGE': "Change",
            'ACTIVITY_CA_DOUBLE_GLAZED_ALU_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_DOOR_WOOD_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_DOOR_PVC_CHANGE': "Change",
            'ACTIVITY_CA_SIMPLE_DOOR_ALU_CHANGE': "Change",
            'ACTIVITY_CA_SECURITY_DOOR_WOOD_CHANGE': "Change",
            'ACTIVITY_CA_SECURITY_DOOR_PVC_CHANGE': "Change",
            'ACTIVITY_CA_SECURITY_DOOR_ALU_CHANGE': "Change",
            'ACTIVITY_CA_SHUTTER_MANUAL_CHANGE': "Change",
            'ACTIVITY_CA_SHUTTER_ROLLING_CHANGE': "Change",
            'ACTIVITY_CA_SHUTTER_ROLLING_ELEC_CHANGE': "Change",
            'ACTIVITY_CA_GARAGE_PORTAL_CHANGE': "Change",
            'ACTIVITY_CA_GARAGE_PORTAL_ELECTRIC_CHANGE': "Change",
            'ACTIVITY_EL_PLUG_CHANGE': "Change",
            'ACTIVITY_EL_SWITCH_CHANGE': "Change",
            'ACTIVITY_EL_INTERCOM_CHANGE': "Change",
            'ACTIVITY_EL_SWITCHBOARD_CHANGE': "Change",
            'ACTIVITY_EL_CIRCUIT_BREAKER_CHANGE': "Change",
            'ACTIVITY_PL_WC_INSTALL': "Install",
            'ACTIVITY_PL_SHOWER_INSTALL': "Install",
            'ACTIVITY_PL_BATH_INSTALL': "Install",
            'ACTIVITY_PL_SINK_INSTALL': "Install",
            'ACTIVITY_PL_WATER_VALVE_INSTALL': "Install",
            'ACTIVITY_PL_HOT_WATER_TANK_INSTALL': "Install",
            'ACTIVITY_PL_RADIATOR_INSTALL': "Install",
            'ACTIVITY_PL_BOILER_WATER_HEATER_INSTALL': "Install",
            'ACTIVITY_LO_SIMPLE_DOOR_INSTALL': "Install",
            'ACTIVITY_LO_SECURITY_DOOR_INSTALL': "Install",
            'ACTIVITY_LO_SIMPLE_LOCK_INSTALL': "Install",
            'ACTIVITY_LO_SECURITY_LOCK_INSTALL': "Install",
            'ACTIVITY_LO_ELECTRIC_LOCK_INSTALL': "Install",
            'ACTIVITY_LO_PORTAL_INSTALL': "Install",
            'ACTIVITY_LO_ELECTRIC_PORTAL_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_GLAZED_WOOD_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_GLAZED_PVC_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_GLAZED_ALU_INSTALL': "Install",
            'ACTIVITY_CA_DOUBLE_GLAZED_WOOD_INSTALL': "Install",
            'ACTIVITY_CA_DOUBLE_GLAZED_PVC_INSTALL': "Install",
            'ACTIVITY_CA_DOUBLE_GLAZED_ALU_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_DOOR_WOOD_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_DOOR_PVC_INSTALL': "Install",
            'ACTIVITY_CA_SIMPLE_DOOR_ALU_INSTALL': "Install",
            'ACTIVITY_CA_SECURITY_DOOR_WOOD_INSTALL': "Install",
            'ACTIVITY_CA_SECURITY_DOOR_PVC_INSTALL': "Install",
            'ACTIVITY_CA_SECURITY_DOOR_ALU_INSTALL': "Install",
            'ACTIVITY_CA_SHUTTER_MANUAL_INSTALL': "Install",
            'ACTIVITY_CA_SHUTTER_ROLLING_INSTALL': "Install",
            'ACTIVITY_CA_SHUTTER_ROLLING_ELEC_INSTALL': "Install",
            'ACTIVITY_CA_GARAGE_PORTAL_INSTALL': "Install",
            'ACTIVITY_CA_GARAGE_PORTAL_ELECTRIC_INSTALL': "Install",
            'ACTIVITY_EL_PLUG_INSTALL': "Install",
            'ACTIVITY_EL_SWITCH_INSTALL': "Install",
            'ACTIVITY_EL_INTERCOM_INSTALL': "Install",
            'ACTIVITY_EL_SWITCHBOARD_INSTALL': "Install",
            'ACTIVITY_EL_CIRCUIT_BREAKER_INSTALL': "Install",
            'ACTIVITY_LO_SIMPLE_DOOR_UNBLOCK': "Unblock",
            'ACTIVITY_LO_SECURITY_DOOR_UNBLOCK': "Unblock",
            'ACTIVITY_LO_SIMPLE_LOCK_UNBLOCK': "Unblock",
            'ACTIVITY_LO_SECURITY_LOCK_UNBLOCK': "Unblock",
            'ACTIVITY_LO_ELECTRIC_LOCK_UNBLOCK': "Unblock",
            'ACTIVITY_LO_PORTAL_UNBLOCK': "Unblock",
            'ACTIVITY_LO_ELECTRIC_PORTAL_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SIMPLE_DOOR_WOOD_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SIMPLE_DOOR_PVC_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SIMPLE_DOOR_ALU_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SECURITY_DOOR_WOOD_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SECURITY_DOOR_PVC_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SECURITY_DOOR_ALU_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SHUTTER_MANUAL_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SHUTTER_ROLLING_UNBLOCK': "Unblock",
            'ACTIVITY_CA_SHUTTER_ROLLING_ELEC_UNBLOCK': "Unblock",
            'ACTIVITY_CA_GARAGE_PORTAL_UNBLOCK': "Unblock",
            'ACTIVITY_CA_GARAGE_PORTAL_ELECTRIC_UNBLOCK': "Unblock",
            'ACTIVITY_PL_WC_LEAK': "Leak",
            'ACTIVITY_PL_SHOWER_LEAK': "Leak",
            'ACTIVITY_PL_BATH_LEAK': "Leak",
            'ACTIVITY_PL_SINK_LEAK': "Leak",
            'ACTIVITY_PL_WATER_VALVE_LEAK': "Leak",
            'ACTIVITY_PL_HOT_WATER_TANK_LEAK': "Leak",
            'ACTIVITY_PL_RADIATOR_LEAK': "Leak",
            'ACTIVITY_PL_BOILER_WATER_HEATER_LEAK': "Leak",
            'ACTIVITY_PL_WC_UNCORK': "Uncork",
            'ACTIVITY_PL_SHOWER_UNCORK': "Uncork",
            'ACTIVITY_PL_BATH_UNCORK': "Uncork",
            'ACTIVITY_PL_SINK_UNCORK': "Uncork",
            'ACTIVITY_PL_WATER_VALVE_UNCORK': "Uncork",
            'ACTIVITY_PL_HOT_WATER_TANK_UNCORK': "Uncork",
            'ACTIVITY_PL_RADIATOR_UNCORK': "Uncork",
            'ACTIVITY_PL_BOILER_WATER_HEATER_UNCORK': "Uncork",
            'ACTIVITY_PA_EXTERIOR_WALL_M30': "Over 30m2",
            'ACTIVITY_PA_EXTERIOR_FENCE_M30': "Over 30m2",
            'ACTIVITY_PA_INTERIOR_ROOM_M30': "Over 30m2",
            'ACTIVITY_PA_INTERIOR_WALL_M30': "Over 30m2",
            'ACTIVITY_PA_INTERIOR_CEILING_M30': "Over 30m2",
            'ACTIVITY_TI_FLOOR_M30': "Over 30m2",
            'ACTIVITY_TI_WALL_M30': "Over 30m2",
            'ACTIVITY_TI_FLOOR_AND_WALL_M30': "Over 30m2",
            'ACTIVITY_PA_EXTERIOR_WALL_P30': "Less than 30m2",
            'ACTIVITY_PA_EXTERIOR_FENCE_P30': "Less than 30m2",
            'ACTIVITY_PA_INTERIOR_ROOM_P30': "Less than 30m2",
            'ACTIVITY_PA_INTERIOR_WALL_P30': "Less than 30m2",
            'ACTIVITY_PA_INTERIOR_CEILING_P30': "Less than 30m2",
            'ACTIVITY_TI_FLOOR_P30': "Less than 30m2",
            'ACTIVITY_TI_WALL_P30': "Less than 30m2",
            'ACTIVITY_TI_FLOOR_AND_WALL_P30': "Less than 30m2"
        });
    }])
;
